- platform: pushbullet
  api_key: !secret pushbullet_api_key
  name: pushbullet

- platform: ios
  name: ios
  target: !secret ios_target

- platform: richsmtp
  name: gmail
  server: smtp.gmail.com
  port: 587
  sender: !secret hass_email
  starttls: 1
  username: !secret hass_email
  password: !secret hass_email_pw
  recipient: !secret myemail
  timeout: 60
  product_name: UgePiso

- platform: kodi
  name: kodi
  host: !secret kodi_host
  port: !secret kodi_port
  username: !secret kodi_user
  password: !secret kodi_pw

- platform: mytelegram
  name: telegram_bot
  api_key: !secret telegram_bot_api_key
  user_id:
    Eugenio: !secret telegram_bot_chat_id_admin
    Carmen: !secret telegram_bot_chat_id_2
#  chat_id: !secret telegram_bot_chat_id_admin