homeassistant:
  name: Piso
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: !secret elevation
  time_zone: Europe/Madrid
  customize: !include customize.yaml

http:
  base_url: !secret base_url
  api_password: !secret hass_pw
  ip_ban_enabled: True
  login_attempts_threshold: 5
  # SSL certs working in NGINX config
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key

####################################################
#                     Includes                     #
####################################################
input_boolean: !include inputs/input_booleans.yaml
input_slider: !include inputs/input_sliders.yaml
input_select: !include inputs/input_selects.yaml
camera: !include devices/cameras.yaml
light: !include devices/lights.yaml
binary_sensor: !include devices/binary_sensors.yaml
sensor: !include devices/sensors.yaml
switch: !include devices/switches.yaml
shell_command: !include shell_commands.yaml
media_player: !include devices/media_players.yaml
scene: !include_dir_merge_list scenes/
weblink: !include web_links.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_named scripts/
panel_iframe: !include iframe_panels.yaml
ios: !include ios_app.yaml
device_tracker: !include devices/device_trackers.yaml
notify: !include notify.yaml
group: !include groups.yaml

####################################################
#                 Custom platforms                 #
####################################################
enerpi:
  enerpi_rpi3:
    host: 192.168.1.44
    name: enerPI
    scan_interval: 10
    monitored_variables:
      - power
      - ldr
#      - ref
    pngtiles_refresh: 300
    dpi: 200

####################################################
#                     Enables                      #
####################################################
logger:
  default: info
  logs:
    netdisco: error
    homeassistant.core: warn
    homeassistant.bootstrap: error
    homeassistant.services.notify: debug
    requests.packages.urllib3.connectionpool: warn
    homeassistant.components.camera: error
    homeassistant.components.device_tracker: warn
    homeassistant.components.netdisco: error
    homeassistant.components.http: warn
    homeassistant.components.media_player: warn
    homeassistant.components.switch: error
    homeassistant.components.sensor: warn
    homeassistant.components.notify.ios: debug
    # custom_components.enerpi: debug
    # custom_components.switch: error

browser:
conversation:
discovery:
frontend:
sun:
updater:

history:
  include:
    domains:
      - sun
      - device_tracker
      - binary_sensor
      - switch
      - light
    entities:
      - sensor.villena_temperature
      - sensor.villena_humidity
      - sensor.salon_humidity
      - sensor.salon_temperature
      - sensor.t_salon
      - sensor.temp_stats_mean
      - sensor.yr

logbook:
  include:
    domains:
      - switch
      - media_player
      - sun
      - binary_sensor
#      - device_tracker
    entities:
      - sensor.heating
      - sensor.calefaccion

recorder:
  purge_days: !secret recorder_purge_days
  db_url: !secret recorder_db_url
