homeassistant:
  name: Piso
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: !secret elevation
  time_zone: !secret time_zone
  customize: !include frontend/customize.yaml

# This will override the default home zone
zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 125
  icon: mdi:castle
zone 2:
  name: !secret z2_name
  latitude: !secret z2_latitude
  longitude: !secret z2_longitude
  radius: !secret z2_radius
  icon: !secret z2_icon
zone 3:
  name: !secret z3_name
  latitude: !secret z3_latitude
  longitude: !secret z3_longitude
  radius: !secret z3_radius
  icon: !secret z3_icon

http:
  base_url: !secret base_url
  api_password: !secret hass_pw
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5
  # SSL certs working in NGINX config
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key

####################################################
#                     Includes                     #
####################################################
input_boolean: !include inputs/input_booleans.yaml
input_slider: !include inputs/input_sliders.yaml
input_select: !include inputs/input_selects.yaml
camera: !include devices/cameras.yaml
light: !include devices/lights.yaml
binary_sensor: !include devices/binary_sensors.yaml
sensor: !include devices/sensors.yaml
switch: !include devices/switches.yaml
media_player: !include devices/media_players.yaml
device_tracker: !include devices/device_trackers.yaml
shell_command: !include shell/shell_commands.yaml
scene: !include_dir_merge_list scenes/
automation: !include_dir_merge_list automation/
script: !include_dir_named scripts/
ios: !include notify/ios_app.yaml
notify: !include notify/notify.yaml
panel_iframe: !include frontend/iframe_panels.yaml
weblink: !include frontend/web_links.yaml
group: !include frontend/groups.yaml

####################################################
#                 Custom platforms                 #
####################################################
enerpi:
  enerpi_rpi3:
    host: !secret enerpi_host
    name: enerPI
    scan_interval: 30
    delta_refresh: 1000
    monitored_variables:
      - power
      - ldr
    pngtiles_refresh: 300

########################################
# MQTT
########################################
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  protocol: 3.1

########################################
# influxdb export
########################################
influxdb: !include influxdb.yaml

####################################################
#                     Telegram webhooks            #
####################################################
mytelegram_webhooks:
#  trusted_networks:
#    - 149.154.167.197/32
#    - 149.154.167.198/31
  api_key: !secret telegram_bot_api_key
  user_id:
    Eugenio: !secret telegram_bot_chat_id_admin
    Carmen: !secret telegram_bot_chat_id_2

####################################################
#                     Enables                      #
####################################################
logger:
  default: warn
  logs:
    netdisco: error
    homeassistant.setup: error
    homeassistant.bootstrap: info
#    homeassistant.components.automation: info
    homeassistant.components.camera: error
    homeassistant.components.netdisco: error
    homeassistant.components.script: info
#    homeassistant.components.media_player: info
    homeassistant.components.tts: debug
    custom_components.notify.richsmtp: info
    custom_components.notify.mytelegram: info
    custom_components.mytelegram_webhooks: info
    # custom_components.sensor.enerweb: info
    # custom_components.enerpi: info
    # custom_components.switch: error

browser:
conversation:
discovery:
frontend:
sun:
updater:
config:

# Text to speech
tts:
  platform: google
  language: 'es'

history:
  include:
    domains:
      - sun
      - binary_sensor
      - light
      - media_player
    entities:
      - sensor.calefaccion
#      - sensor.cpu_use
#      - sensor.cpu_use_rpi2h
#      - sensor.cpu_use_rpi2mpd
      - sensor.dht22_dormitorio_humidity_rpi2mpd
      - sensor.dht22_dormitorio_temperature_rpi2mpd
      - sensor.dht22_humidity_rpi2h
      - sensor.dht22_temperature_rpi2h
#      - sensor.disk_use__rpi2h
#      - sensor.disk_use__rpi2mpd
#      - sensor.disk_use_home
#      - sensor.enerpi
#      - sensor.enerpi_ldr
#      - sensor.enerpi_power
      - sensor.galeria_dht22_humidity
      - sensor.galeria_dht22_temperature
      - sensor.galeria_acs
      - sensor.galeria_impulsion_calefaccion
      - sensor.galeria_retorno_calefaccion
#      - sensor.iphone_battery_level
#      - sensor.iphone_battery_state
#      - sensor.temperature_rpi2h
#      - sensor.humidity_rpi2h
      - sensor.pressure_rpi2h
      - sensor.ram_free
      - sensor.ram_free_rpi2h
      - sensor.ram_free_rpi2mpd
      - sensor.salon_humidity
      - sensor.salon_temperature
      - sensor.t_salon
      - sensor.temperatura_dormitorio_rpi2mpd
      - sensor.temperatura_estudio_rpi2h
#      - sensor.villena_cloud_coverage
#      - sensor.villena_condition
#      - sensor.villena_forecast
      - sensor.villena_humidity
      - sensor.villena_pressure
      - sensor.villena_rain
      - sensor.villena_temperature
#      - sensor.villena_wind_speed
      - sensor.yr_symbol
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload
      - switch.altavoz
      - switch.caldera
      - switch.calefactor
      - switch.camara
      - switch.cocina
      - switch.impresora
      - switch.kodi_tv_salon
      - switch.switch_master_alarm
      - switch.alarm_clock_status
      - switch.toggle_config_kodi_ambilight
      - switch.toggle_kodi_ambilight
      - group.eugenio
      - group.family
      - group.mary
      - device_tracker.hass_iphone
      - device_tracker.hass_iphonese
      - device_tracker.iphone
      - device_tracker.iphone_bt
      - device_tracker.iphone_se
      - device_tracker.iphone_se_bt

logbook:
  include:
    domains:
      - switch
      - media_player
      - sun
      - script
      - automation
    entities:
      - sensor.heating
      - sensor.calefaccion
      - group.eugenio
      - group.family
      - group.mary

recorder:
  purge_days: !secret recorder_purge_days
  db_url: !secret recorder_db_url
