homeassistant:
  name: Piso
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: !secret elevation
  time_zone: !secret time_zone
  customize: !include frontend/customize.yaml

# This will override the default home zone
zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 125
  icon: mdi:castle
zone 2:
  name: !secret z2_name
  latitude: !secret z2_latitude
  longitude: !secret z2_longitude
  radius: !secret z2_radius
  icon: !secret z2_icon

http:
  base_url: !secret base_url
  api_password: !secret hass_pw
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5
  # SSL certs working in NGINX config
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key

####################################################
#                     Includes                     #
####################################################
input_boolean: !include inputs/input_booleans.yaml
input_slider: !include inputs/input_sliders.yaml
input_select: !include inputs/input_selects.yaml
camera: !include devices/cameras.yaml
light: !include devices/lights.yaml
binary_sensor: !include devices/binary_sensors.yaml
sensor: !include devices/sensors.yaml
switch: !include devices/switches.yaml
media_player: !include devices/media_players.yaml
device_tracker: !include devices/device_trackers.yaml
shell_command: !include shell/shell_commands.yaml
scene: !include_dir_merge_list scenes/
automation: !include_dir_merge_list automation/
script: !include_dir_named scripts/
ios: !include notify/ios_app.yaml
notify: !include notify/notify.yaml
panel_iframe: !include frontend/iframe_panels.yaml
weblink: !include frontend/web_links.yaml
group: !include frontend/groups.yaml

########################################
# MQTT
########################################
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 120
  username: !secret mqtt_username
  password: !secret mqtt_password
#  birth_message:
#    topic: 'hass/status'
#    payload: 'online'
#  will_message:
#    topic: 'hass/status'
#    payload: 'offline'
  protocol: 3.1

####################################################
#                 Custom platforms                 #
####################################################
enerpi:
  enerpi_rpi3:
    host: !secret enerpi_host
    name: enerPI
    scan_interval: 30
    delta_refresh: 1000
    monitored_variables:
      - power
      - ldr
    pngtiles_refresh: 300

####################################################
#                     Telegram BOT                 #
####################################################
mytelegram_bot:
  platform: webhooks
  api_key: !secret telegram_bot_api_key
  allowed_chat_ids:
    - !secret telegram_bot_chat_id_admin
    - !secret telegram_bot_chat_id_2

####################################################
#                     Enables                      #
####################################################
logger: !include database/logger.yaml
browser:
#conversation:
discovery:
frontend:
sun:
updater:
config:
tts:
  # Text to speech
  platform: google
  language: 'es'

########################################
# Databases
########################################
#influxdb: !include database/influxdb.yaml
myinfluxdb: !include database/influxdb.yaml
history: !include database/history.yaml
logbook: !include database/logbook.yaml
recorder:
  purge_days: !secret recorder_purge_days
  db_url: !secret recorder_db_url
