homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: !secret elevation
  time_zone: !secret time_zone
  customize: !include frontend/customize.yaml
  packages:  !include_dir_named packages

http:
  base_url: !secret base_url
  api_password: !secret hass_pw
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 5
  # SSL certs working in NGINX config
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 120
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1

panel_iframe:
  grafana_access:
    title: Grafana
    url: !secret grafana_url
    icon: mdi:chart-areaspline
  enerpiweb_access:
    title: enerPI
    url: !secret enerpi_url
    icon: mdi:power-plug
  kodi_access:
    title: Kodi
    url: !secret kodi_url
    icon: mdi:kodi
  motioneye_access:
    title: MotionEye
    url: !secret motioneye_url
    icon: mdi:video

scene: !include_dir_merge_list scenes/
automation: !include_dir_merge_list automation/
script: !include_dir_named scripts/
logger: !include database/logger.yaml
group: !include frontend/groups.yaml
browser:
#conversation:
discovery:
frontend:
sun:
updater:
config:
tts:  # Text to speech
  platform: google
  language: 'es'

########################################
# Databases
########################################
#influxdb: !include database/influxdb.yaml
myinfluxdb: !include database/influxdb.yaml
history: !include database/history.yaml
logbook: !include database/logbook.yaml
recorder:
  purge_days: !secret recorder_purge_days
  db_url: !secret recorder_db_url
