homeassistant:
  name: Piso
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: !secret elevation
  time_zone: Europe/Madrid
  customize: !include customize.yaml

http:
  api_password: !secret hass_pw
  ip_ban_enabled: True
  login_attempts_threshold: 5
  # SSL certs working in NGINX config
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key

####################################################
#                     Includes                     #
####################################################
binary_sensor: !include devices/binary_sensors.yaml
camera: !include devices/cameras.yaml
device_tracker: !include devices/device_trackers.yaml
group: !include groups.yaml
input_boolean: !include inputs/input_booleans.yaml
input_slider: !include inputs/input_sliders.yaml
input_select: !include inputs/input_selects.yaml
light: !include devices/lights.yaml
media_player: !include devices/media_players.yaml
notify: !include notify.yaml
sensor: !include devices/sensors.yaml
switch: !include devices/switches.yaml
weblink: !include web_links.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_named scripts/
scene: !include_dir_merge_list scenes/

####################################################
#                 Custom platform                  #
####################################################
enerpi:
  enerpi_rpi3:
    host: 192.168.1.44
    name: enerPI
    scan_interval: 10
    monitored_variables:
      - power
      - ldr
#      - ref
    pngtiles_refresh: 300
    dpi: 200

####################################################
#                     Enables                      #
####################################################
logger:
  default: info
  logs:
    netdisco: error
    homeassistant.core: warn
    homeassistant.bootstrap: error
    homeassistant.services.notify: debug
    requests.packages.urllib3.connectionpool: warn
    homeassistant.components.device_tracker: warn
    homeassistant.components.netdisco: error
    homeassistant.components.http: warn
    homeassistant.components.media_player: warn
    homeassistant.components.switch: error
    homeassistant.components.sensor: warn
    homeassistant.components.camera: error
    # custom_components.enerpi: debug
    # custom_components.switch: error

browser:
conversation:
discovery:
frontend:
sun:
updater:

history:
  include:
    domains:
      - sun
      - device_tracker
      - binary_sensor
      - switch
      - light
    entities:
      - sensor.villena_temperature
      - sensor.villena_humidity
      - sensor.salon_humidity
      - sensor.salon_temperature
      - sensor.t_salon
      - sensor.temp_stats_mean
      - sensor.yr

logbook:
  include:
    domains:
      - switch
      - media_player
      - sun
      - binary_sensor
#      - device_tracker
    entities:
      - sensor.heating
      - sensor.calefaccion

recorder:
  purge_days: !secret recorder_purge_days
  db_url: !secret recorder_db_url

####################################################
#                     iOS platform                 #
####################################################
# TODO refinar y hacer funcionar las etiquetas de respuesta
# iOS App
ios:
  push_categories:
    - name: Away
      identifier: 'AWAY'
      actions:
        - identifier: 'ALARM_ARM_NOW'
          title: 'Arm'
          activationMode: 'background'
          authenticationRequired: no
          destructive: yes
          behavior: 'default'
          context: 'minimal'
        - identifier: 'ALARM_CANCEL'
          activationMode: 'background'
          authenticationRequired: yes
          destructive: no
          behavior: 'default'
          context: 'minimal'

    - name: Alarm
      identifier: 'ALARMSOUNDED'
      actions:
        - identifier: 'ALARM_SLEEP'
          title: 'Sleep'
          activationMode: 'background'
          authenticationRequired: no
          destructive: no
          behavior: 'default'
          context: 'default'
        - identifier: 'ALARM_CANCEL'
          title: 'Disarm'
          activationMode: 'background'
          authenticationRequired: no
          destructive: no
          behavior: 'default'
          context: 'default'

    - name: Confirm
      identifier: 'CONFIRM'
      actions:
        - identifier: 'CONFIRM_OK'
          title: 'OK?'
          activationMode: 'background'
          authenticationRequired: no
          destructive: no
          behavior: 'default'
          context: 'default'

#  push_categories: # Defines actionable notifications. Categories are groups of actions. You specify the category in the notification.
    - name: Other
      identifier: 'OTHER' # Must be unique and ALL CAPS
      actions:
        - identifier: 'OTHERSOUNDALARM' # Must be unique and ALL CAPS
          title: 'Sound Alarm' # Needs to be short!
          activationMode: 'background' # or background. The mode in which to run the app when the action is performed.
          authenticationRequired: yes # A Boolean value indicating whether the user must unlock the device before the action is performed.
          destructive: yes # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
          behavior: 'default' # or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
          context: 'default' # or Minimal. Default = In this context, the full UI is displayed for the notification’s alert. You may specify up to four custom actions in this context. Minimal = In this context, a minimal UI is displayed for the notification’s alert. You may specify up to two custom actions in this context.
        - identifier: 'OTHERSILENCEALARM' # Must be unique and ALL CAPS
          title: 'Silence Alarm' # Needs to be short!
          activationMode: 'background' # or background. The mode in which to run the app when the action is performed.
          authenticationRequired: yes # A Boolean value indicating whether the user must unlock the device before the action is performed.
          destructive: no # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
          behavior: 'TextInput' # Default or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
          context: 'default' # or Minimal. Default = In this context, the full UI is displayed for the notification’s alert. You may specify up to four custom actions in this context. Minimal = In this context, a minimal UI is displayed for the notification’s alert. You may specify up to two custom actions in this context.
          textInputButtonTitle: 'Silencio!' # Only for iOS 10 when behavior is TextInput.
          textInputPlaceholder: '...' # Only for iOS 10 when behavior is TextInput.
          parameters: # iOS 9 only. Use this dictionary to specify any behavior-specific data for the action. For example, if you set behavior to TextInput you can use the UIUserNotificationTextInputActionButtonTitleKey key, which lets you customize the title of the button displayed by the text input interface.
            UIUserNotificationTextInputActionButtonTitleKey: "Silencio!"

####################################################
#                     Shell commands               #
####################################################
# These 'sudo' commands are appended in /etc/sudoers.d/vip, for the HA user only.
shell_command:
  restart_homebridge: 'sudo systemctl restart homebridge'
  start_homebridge: 'sudo systemctl start homebridge'
  stop_homebridge: 'sudo systemctl stop homebridge'
  restart_hass: 'sudo systemctl restart home-assistant@homeassistant'
  stop_hass: 'sudo systemctl stop home-assistant@homeassistant'

####################################################
#               Extra panels (iframes)             #
####################################################
panel_iframe:
  enerpi:
    title: enerPI
    url: !secret enerpi_url
    icon: mdi:power-plug
  kodi:
    title: Kodi
    url: !secret kodi_url
    icon: mdi:kodi
  motioneye:
    title: MotionEye
    url: !secret motioneye_url
    icon: mdi:video
