- platform: pushbullet
  api_key: !secret pushbullet_api_key
  name: pushbullet

- platform: ios
  name: ios
  target: !secret ios_target

- platform: smtp
  name: gmail
  server: smtp.gmail.com
  port: 587
  sender: !secret hass_email
  starttls: 1
  username: !secret hass_email
  password: !secret hass_email_pw
  recipient: !secret myemail

- platform: kodi
  name: kodi
  host: http://192.168.1.56
  port: 8080
  username: !secret kodi_user
  password: !secret kodi_pw