homeassistant:
  name: Dormitorio
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: !secret elevation
  time_zone: Europe/Madrid
  customize: !include customize.yaml

config:

logger:
  default: warn
  logs:
#    homeassistant.loader: info
    homeassistant.bootstrap: info
    requests: error
    homeassistant.components.http: warn
    homeassistant.components.binary_sensor: info
    homeassistant.components.media_player: debug
    custom_components.sensor.myonewire: info
    homeassistant.components.automation: info

http:
  api_password: !secret hass_pw
  ip_ban_enabled: True
  login_attempts_threshold: 10

browser:
frontend:

history:
  include:
    domains:
      - binary_sensor
      - media_player
      - switch
    entities:
      - sensor.dht22_dormitorio_temperature
      - sensor.dht22_dormitorio_humidity
      - sensor.temperatura_dormitorio

logbook:
  include:
    domains:
      - switch
      - media_player
      - script

updater:
recorder:
  purge_days: !secret recorder_purge_days
  db_url: !secret recorder_db_url

switch:
- platform: command_line
  scan_interval: 120
  switches:
    systemd_appdaemon:
      command_on: '/home/homeassistant/.homeassistant/switch_systemd_service.sh appdaemon start'
      command_off: '/home/homeassistant/.homeassistant/switch_systemd_service.sh appdaemon stop'
      command_state: '/home/homeassistant/.homeassistant/switch_systemd_service.sh appdaemon status'
      friendly_name: Appdaemon service
      value_template: '{{ value_json == 1 }}'
    systemd_shairport_sync:
      command_on: '/home/homeassistant/.homeassistant/switch_systemd_service.sh shairport-sync start'
      command_off: '/home/homeassistant/.homeassistant/switch_systemd_service.sh shairport-sync stop'
      command_state: '/home/homeassistant/.homeassistant/switch_systemd_service.sh shairport-sync status'
      friendly_name: Shairport-Sync service
      value_template: '{{ value_json == 1 }}'
    systemd_mpd:
      command_on: '/home/homeassistant/.homeassistant/switch_systemd_service.sh mpd start'
      command_off: '/home/homeassistant/.homeassistant/switch_systemd_service.sh mpd stop'
      command_state: '/home/homeassistant/.homeassistant/switch_systemd_service.sh mpd status'
      friendly_name: MPD service
      value_template: '{{ value_json == 1 }}'
    systemd_mopidy:
      command_on: '/home/homeassistant/.homeassistant/switch_systemd_service.sh mopidy start'
      command_off: '/home/homeassistant/.homeassistant/switch_systemd_service.sh mopidy stop'
      command_state: '/home/homeassistant/.homeassistant/switch_systemd_service.sh mopidy status'
      friendly_name: Mopidy service
      value_template: '{{ value_json == 1 }}'

binary_sensor:
- platform: rpi_gpio
  name: sensores de movimiento
#  device_class: motion
  ports:
    27: PIR Dormitorio
  bouncetime: 50
  pull_mode: "UP"
#
#- platform: rpi_gpio
#  name: sensores digitales
#  ports:
##    19: vibration_sensor_dormitorio_raw
#    26: sound_sensor_dormitorio_raw
#  bouncetime: 50
#  pull_mode: "DOWN"

sensor:
#  - platform: myonewire
#    names:
#      28-80000001595e: Temperatura Dormitorio
#    scan_interval: 40
#    maximum: 50
#    minimum: 5
#
#  - platform: dht
#    sensor: DHT22
#    pin: 24
#    name: dht22_dormitorio
#    scan_interval: 40
#    monitored_conditions:
#      - temperature
#      - humidity

  # BME280 in RPI
  - platform: command_line
    name: Temperatura Dormitorio
    command: "/usr/local/bin/read_bme280 --temperature --i2c-address 0x77"
    unit_of_measurement: "°C"
    value_template: '{{ value |replace(" C", "") | round(2) }}'
    scan_interval: 30

  - platform: command_line
    name: Humedad Dormitorio
    command: "/usr/local/bin/read_bme280 --humidity --i2c-address 0x77"
    unit_of_measurement: "%"
    value_template: '{{ value |replace("％", "") | round(2) }}'
    scan_interval: 30

  - platform: command_line
    name: Presión Dormitorio
    command: "/usr/local/bin/read_bme280 --pressure --i2c-address 0x77"
    unit_of_measurement: "mb"
    value_template: '{{ value |replace(" hPa", "") | round(2) }}'
    scan_interval: 30

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use
      - type: last_boot

media_player:
  - platform: mpd
    host: !secret mpd_host
    port: !secret mpd_port
    location: Mopidy

# Text to speech
tts:
  platform: google
  language: 'es'

weblink:
  entities:
    - name: Master Hass
      url: !secret link_master_hass
    - name: Hass Estudio
      url: !secret link_hass_estudio
    - name: enerPI
      url: !secret link_enerpi
    - name: Mopidy
      url: !secret link_mopidy

shell_command:
  restart_hass: 'sudo systemctl restart home-assistant@homeassistant'
  # Use with caution
  cmd_reboot: 'sudo reboot now'
  cmd_shutdown: 'sudo shutdown now'

script:
  restart_hass:
    alias: Restart HASS
    sequence:
      - service: persistent_notification.create
        data:
          title: 'Reiniciando Home Assistant'
          message: "En unos segundos estará funcionando de nuevo..."
      - delay:
          seconds: 3
      - service: shell_command.restart_hass
  reboot:
    alias: Reiniciar RPI
    sequence:
      - service: persistent_notification.create
        data:
          title: 'Reiniciando RPI'
          message: "En unos minutos estará funcionando de nuevo"
      - delay:
          seconds: 3
      - service: shell_command.cmd_reboot
  shutdown:
    alias: Apagar RPI
    sequence:
      - service: persistent_notification.create
        data:
          title: 'Apagando RPI'
          message: "Espera al menos 30 segundos para desenchufar"
      - delay:
          seconds: 3
      - service: shell_command.cmd_shutdown
  tell_me_ambient_data:
    alias: Léeme las condiciones ambientales
    sequence:
      - service: persistent_notification.create
        data:
          title: 'Condiciones ambientales:'
          message: "La Tª es de {{(states('sensor.temperatura_dormitorio')|float / 2 + states('sensor.dht22_dormitorio_temperature')|float / 2)|round(1)}} ºC y la HR es del {{states('sensor.dht22_dormitorio_humidity')}} %."
      - service: tts.google_say
        entity_id: media_player.mopidy
        data_template:
          message: "La temperatura es de {{(states('sensor.temperatura_dormitorio')|float / 2 + states('sensor.dht22_dormitorio_temperature')|float / 2)|round(1)}} grados y la humedad relativa es del {{states('sensor.dht22_dormitorio_humidity')}} por ciento."
          cache: false

group:
  Dormitorio:
#    - sensor.temperatura_dormitorio
#    - sensor.dht22_dormitorio_temperature
#    - sensor.dht22_dormitorio_humidity
    - sensor.temperatura_dormitorio
    - sensor.humedad_dormitorio
    - sensor.presion_dormitorio
    - binary_sensor.pir_dormitorio
#    - binary_sensor.vibration_sensor
#    - binary_sensor.sound_sensor_dormitorio
#    - binary_sensor.vibration_sensor_raw
#    - binary_sensor.sound_sensor_dormitorio_raw
    - media_player.mopidy

  RPi 2 monitor:
    control: hidden
    entities:
      - sensor.disk_use_
      - sensor.cpu_use
      - sensor.ram_free
      - sensor.last_boot
      - switch.systemd_appdaemon
      - switch.systemd_mpd
      - switch.systemd_mopidy
      - switch.systemd_shairport_sync
      - script.restart_hass
      - script.reboot
      - script.shutdown
      - script.tell_me_ambient_data

  Links:
    - weblink.master_hass
    - weblink.hass_estudio
    - weblink.mopidy
    - weblink.enerpi

  Status:
    name: Home Status
    icon: mdi:castle
    view: yes
    entities:
      - group.dormitorio

  Home Network:
    name: Red local del hogar
    icon: mdi:sitemap
    view: yes
    entities:
      - group.rpi_2_monitor
      - group.links
