# Describes the format for available services for the vacuum robot

send_command:
  description: Send command to the vacuum.
  fields:
    command:
      description: Command to execute
      example: 'set_dnd_timer'
    params:
      description: Parameters for the command
      example: '[22,0,6,0]'

set_fanspeed:
  description: Set the fanspeed.
  fields:
    fanspeed:
      description: Fanspeed, between 0 and 100
      example: '60'

remote_control_start:
  description: Start remote control of the vacuum. You can then move it with `remote_control_move`, when done call `remote_control_stop`.

remote_control_stop:
  description: Stop remote control mode of the vacuum.

remote_control_move:
  description: Remote control the vacuum, make sure you first set it in remote control mode with `remote_control_start`.
  fields:
    velocity:
      description: Speed, between -0.3 - 0.3
      example: '0.2'
    rotation:
      description: Rotation, between -180 degrees and 180 degrees
      example: '90'
    duration:
      description: Duration of the movement?
      example: '1500'

remote_control_move_step:
  description: Remote control the vacuum, only makes one move and then stops.
  fields:
    velocity:
      description: Speed, between -0.3 - 0.3
      example: '0.2'
    rotation:
      description: Rotation, between -180 degrees and 180 degrees
      example: '90'
    duration:
      description: Duration of the movement?
      example: '1500'