homeassistant:
  name: Estudio
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: !secret elevation
  time_zone: Europe/Madrid
  customize: !include customize.yaml

config:

logger:
  default: warn
  logs:
    homeassistant.setup: info
    homeassistant.bootstrap: info
    custom_components.sensor.bme280: info
    requests: error

http:
  api_password: !secret hass_pw
  ip_ban_enabled: True
  login_attempts_threshold: 10

browser:
frontend:
history:
  include:
    domains:
      - binary_sensor
      - switch
      - sensor

logbook:
  include:
    domains:
      - input_boolean
      - switch
      - script

updater:
  include_used_components: true
recorder:
  purge_days: !secret recorder_purge_days
#  db_url: !secret recorder_db_url

switch:
- platform: command_line
  scan_interval: 120
  switches:
    systemd_appdaemon:
      command_on: '/home/homeassistant/.homeassistant/switch_systemd_service.sh appdaemon start'
      command_off: '/home/homeassistant/.homeassistant/switch_systemd_service.sh appdaemon stop'
      command_state: '/home/homeassistant/.homeassistant/switch_systemd_service.sh appdaemon status'
      friendly_name: Appdaemon service
      value_template: '{{ value_json == 1 }}'
    systemd_motioneye:
      command_on: '/home/homeassistant/.homeassistant/switch_systemd_service.sh motioneye start'
      command_off: '/home/homeassistant/.homeassistant/switch_systemd_service.sh motioneye stop'
      command_state: '/home/homeassistant/.homeassistant/switch_systemd_service.sh motioneye status'
      friendly_name: MotionEye service
      value_template: '{{ value_json == 1 }}'

- platform: rpi_gpio
  ports:
    16: estudio_light_relay
  invert_logic: true

binary_sensor:
- platform: rpi_gpio
  ports:
    12: estudio_manual_light_switch
  bouncetime: 2000

- platform: rpi_gpio
  ports:
    27: PIR Estudio
  bouncetime: 100
  pull_mode: "UP"

- platform: rpi_gpio
  ports:
    21: vibration_sensor_raw
  bouncetime: 50
  pull_mode: "DOWN"


sensor:
# BME280 in RPI
  - platform: bme280
    name: estudio
    i2c_address: 0x77
    operation_mode: 2  # forced
    time_standby: 5
    oversampling_temperature: 4
    oversampling_pressure: 4
    oversampling_humidity: 4
    delta_temperature: -0.3
    monitored_conditions:
      - temperature
      - humidity
      - pressure
    scan_interval: 20

# BH1750 in RPI
  - platform: bh1750
    name: estudio_light_level
    operation_mode: continuous_high_res_mode_2
    measurement_delay_ms: 10
    sensibility: 125
    multiplier: 1.5
    scan_interval: 20

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: processor_use
      - type: last_boot

  - platform: command_line
    name: HASS CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

shell_command:
  restart_hass: 'sudo systemctl restart home-assistant@homeassistant'
  # Use with caution
  cmd_reboot: 'sudo reboot now'
  cmd_shutdown: 'sudo shutdown now'

script:
  restart_hass:
    alias: Restart HASS
    sequence:
      - service: persistent_notification.create
        data:
          title: 'Reiniciando Home Assistant'
          message: "En unos segundos estará funcionando de nuevo..."
      - delay:
          seconds: 3
      - service: shell_command.restart_hass
  reboot:
    alias: Reiniciar RPI
    sequence:
      - service: persistent_notification.create
        data:
          title: 'Reiniciando Raspberry PI'
          message: "En unos minutos estará funcionando de nuevo"
      - delay:
          seconds: 3
      - service: shell_command.cmd_reboot
  shutdown:
    alias: Apagar RPI
    sequence:
      - service: persistent_notification.create
        data:
          title: 'Apagando Raspberry PI'
          message: "Espera al menos 30 segundos para desenchufar"
      - delay:
          seconds: 3
      - service: shell_command.cmd_shutdown

weblink:
  entities:
    - name: Master Hass
      url: !secret master_hass_url
    - name: Hass Dormitorio
      url: !secret hass_dormitorio_url
    - name: MotionEye
      url: !secret motioneye_url
    - name: enerPI
      url: !secret enerpi_url

group:
  Estudio:
    - sensor.estudio_temperature
    - sensor.estudio_humidity
    - sensor.estudio_pressure
    - binary_sensor.estudio_manual_light_switch
    - switch.estudio_light_relay

  Movimiento:
    - binary_sensor.pir_estudio
    - binary_sensor.vibration_sensor
    - binary_sensor.sound_sensor
    - binary_sensor.vibration_sensor_raw
    - binary_sensor.sound_sensor_raw

  RPi 2 SenseHat monitor:
    control: hidden
    entities:
      - sensor.hass_cpu_temperature
      - sensor.disk_use_
      - sensor.cpu_use
      - sensor.ram_free
      - sensor.last_boot
      - switch.systemd_appdaemon
      - switch.systemd_motioneye
      - script.restart_hass
      - script.reboot
      - script.shutdown

  Links:
    - weblink.master_hass
    - weblink.hass_dormitorio
    - weblink.motioneye
    - weblink.enerpi
