- platform: rpi_gpio
  name: Movimiento Salón
  device_class: motion
  ports:
    18: PIR Salón
  bouncetime: 50
  pull_mode: "UP"
#  invert_logic: true

#- platform: mqtt
#  state_topic: "hass/status"
#  name: 'HA Status'
#  payload_on: "online"
#  payload_off: "offline"
#  device_class: connectivity

- platform: mqtt
  state_topic: !secret mqtt_topic_esp1_pir
  name: esp1_PIR
#  qos (Optional): The maximum QoS level of the state topic. Default is 0.
  payload_on: "on"
  payload_off: "off"
  device_class: motion
#- platform: mqtt
#  state_topic: !secret mqtt_topic_esp1_vibro
#  name: esp1_Vibro
##  qos (Optional): The maximum QoS level of the state topic. Default is 0.
#  payload_on: "on"
#  payload_off: "off"
#  device_class: vibration
- platform: mqtt
  state_topic: !secret mqtt_topic_esp1_light
  name: esp1_Light
#  qos (Optional): The maximum QoS level of the state topic. Default is 0.
  payload_on: "on"
  payload_off: "off"
  device_class: light
- platform: mqtt
  state_topic: !secret mqtt_topic_esp1_online
  name: Cocina Online
#  qos (Optional): The maximum QoS level of the state topic. Default is 0.
  payload_on: "on"
  payload_off: "off"
  device_class: connectivity

- platform: mqtt
  state_topic: !secret mqtt_topic_esp2_pir
  name: esp2_PIR
#  qos (Optional): The maximum QoS level of the state topic. Default is 0.
  payload_on: "on"
  payload_off: "off"
  device_class: motion
- platform: mqtt
  state_topic: !secret mqtt_topic_esp2_vibro
  name: esp2_Vibro
#  qos (Optional): The maximum QoS level of the state topic. Default is 0.
  payload_on: "on"
  payload_off: "off"
  device_class: vibration
- platform: mqtt
  state_topic: !secret mqtt_topic_esp2_light
  name: esp2_Light
#  qos (Optional): The maximum QoS level of the state topic. Default is 0.
  payload_on: "on"
  payload_off: "off"
  device_class: light
- platform: mqtt
  state_topic: !secret mqtt_topic_esp2_online
  name: Esp2 Online
#  qos (Optional): The maximum QoS level of the state topic. Default is 0.
  payload_on: "on"
  payload_off: "off"
  device_class: connectivity

- platform: command_line
  name: Internet Online
  command: ping -W 1 -c 1 8.8.8.8 > /dev/null 2>&1 && echo success || echo fail
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 120

- platform: command_line
  name: Router ON
  command: ping -W 1 -c 1 192.168.1.1 > /dev/null 2>&1 && echo success || echo fail
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 240

- platform: command_line
  name: Pushbullet Online
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh pushbullet"
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 240

- platform: command_line
  name: Email Online
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh richsmtp"
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 240

- platform: command_line
  name: Telegram Online
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh mytelegram"
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 240

- platform: command_line
  name: iOS Online
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh ios"
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 240

- platform: command_line
  name: Kodi Online
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh kodi"
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 240

- platform: command_line
  name: Database OK
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh recorder"
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 180

- platform: template
  sensors:
    heating:
      friendly_name: Calefacción encendida
      device_class: heat
      value_template: "{{states.sensor.calefaccion.state != 'off'}}"
      entity_id:
        - sensor.calefaccion
    services_notok:
      friendly_name: Problemas
      device_class: safety
      value_template: >
        {{
         (states.binary_sensor.kodi_online.state == 'off') or
         (states.binary_sensor.pushbullet_online.state == 'off') or
         (states.binary_sensor.email_online.state == 'off') or
         (states.binary_sensor.ios_online.state == 'off') or
         (states.binary_sensor.telegram_online.state == 'off') or
         (states.binary_sensor.database_ok.state == 'off') or
         (states.binary_sensor.router_on.state == 'off') or
         (states.binary_sensor.internet_online.state == 'off') or
         (states.sensor.ip_externa.state != 'XX.XX.XX.XX') or
         (states.binary_sensor.cocina_online.state == 'off') or
         (states.switch.systemd_appdaemon.state == 'off') or
         (states.switch.systemd_homebridge.state == 'off')
         }}
      entity_id:
        - binary_sensor.kodi_online
        - binary_sensor.pushbullet_online
        - binary_sensor.email_online
        - binary_sensor.ios_online
        - binary_sensor.telegram_online
        - binary_sensor.database_ok
        - binary_sensor.router_on
        - binary_sensor.cocina_online
        - binary_sensor.internet_online
        - sensor.ip_externa
        - switch.systemd_appdaemon
        - switch.systemd_homebridge

- platform: dummy
  sensors:
    motioncam_estudio:
      friendly_name: Vídeo-Mov. en Estudio
      device_class: motion
    motioncam_salon:
      friendly_name: Vídeo-Mov. en Salón
      device_class: motion
    pir_estudio_rpi2h:
      friendly_name: Movimiento en Estudio
      device_class: motion
    pir_dormitorio_rpi2mpd:
      friendly_name: Movimiento en Dormitorio
      device_class: motion
    vibration_sensor_rpi2h:
      friendly_name: Vibración en Estudio
      device_class: vibration
#    sound_sensor_rpi2h:
#      friendly_name: Sonido en Estudio
#      device_class: sound

# binary_sensor.workday_sensor
- platform: workday
  country: !secret country_code
  province: !secret province_code
#  workdays: List of workdays (defaults to mon, tue, wed, thu, fri).
#  excludes: List of workday excludes (defaults to sat, sun, holiday).
