################
# LOCAL CAMERA
################
# RPI Camera
- platform: rpi_camera
  name: PiCamera Salón
  image_width: 1024
  image_height: 768
  image_quality: 70
  image_rotation: 180
  timelapse: 1000
#  horizontal_flip: 1
#  vertical_flip: 0
  file_path: /home/homeassistant/picamera/image.jpg

####################
# MOTIONEYE CAMERAS
####################
# RPI Camera in Slave HASS
#- platform: generic
#  name: PiCamera Estudio
#  still_image_url: !secret picamera_slave_hass
#- platform: mjpeg
#  name: PiCamera Estudio
#  mjpeg_url: http://192.168.1.46:8082
- platform: generic
  name: PiCamera Estudio
  still_image_url: http://192.168.1.46:8765/picture/2/current/

# ESCAM QF001 cheap chinese camera (as still images - generic, or mjpeg stream)
- platform: generic
  name: ESCAM QF001
  still_image_url: http://192.168.1.46:8765/picture/1/current/
#- platform: mjpeg
#  name: ESCAM QF001
#  mjpeg_url: http://192.168.1.46:8081

################
# OTHER CAMERAS
################
# GMaps family location:
- platform: generic
  name: Where are we?
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={% if states.device_tracker.iphone.attributes.latitude %}{{ states.device_tracker.iphone.attributes.latitude }},{{ states.device_tracker.iphone.attributes.longitude }}{% else %}{{ states.zone.home.attributes.latitude }},{{ states.zone.home.attributes.longitude }}{% endif %}&zoom=13&size=500x500&scale=2&maptype=roadmap&markers=color:{% if states.device_tracker.iphone.attributes.latitude %}green{% else %}red{% endif %}%7Clabel:E%7C{% if states.device_tracker.iphone.attributes.latitude %}{{ states.device_tracker.iphone.attributes.latitude }},{{ states.device_tracker.iphone.attributes.longitude }}{% else %}{{ states.zone.home.attributes.latitude }},{{ states.zone.home.attributes.longitude }}{% endif %}&markers=color:{% if states.device_tracker.iphone_5s.attributes.latitude %}blue{% else %}red{% endif %}%7Clabel:C%7C{% if states.device_tracker.iphone_5s.attributes.latitude %}{{ states.device_tracker.iphone_5s.attributes.latitude }},{{ states.device_tracker.iphone_5s.attributes.longitude }}{% else %}{{ states.zone.home.attributes.latitude }},{{ states.zone.home.attributes.longitude }}{% endif %}
  limit_refetch_to_url_change: true

