- platform: kodi
  host: !secret kodi_host
  port: !secret kodi_port
  name: Kodi
  username: !secret kodi_user
  password: !secret kodi_pw
  enable_websocket: true
  turn_off_action: quit

- platform: mpd
  host: !secret mpd_host
  port: !secret mpd_port
  name: Dormitorio (Mopidy)
#  scan_interval: 60
