- platform: kodi
  host: 192.168.1.56
  port: 8080
  name: Kodi
  username: !secret kodi_user
  password: !secret kodi_pw
  turn_off_action: quit

- platform: mpd
#  host: 192.168.1.51  # wifi
  host: 192.168.1.52
  location: Dormitorio (Mopidy)
