# RPI hardware-present sensors:
- platform: myonewire
  names:
    28-8000000152ed: T_Salón
  scan_interval: 30
  maximum: 45
  minimum: 5

- platform: dht
  sensor: DHT22
  pin: 22
  name: Salón
  scan_interval: 30
  monitored_conditions:
    - temperature
    - humidity

- platform: mqtt
  state_topic: !secret mqtt_topic_esp1_hum
  name: 'esp1_Humidity'
  unit_of_measurement: '%'
  expire_after: 180
- platform: mqtt
  state_topic: !secret mqtt_topic_esp1_temp
  name: 'esp1_Temperature'
  unit_of_measurement: 'ºC'
  expire_after: 180
- platform: mqtt
  state_topic: !secret mqtt_topic_esp1_light_analog
  name: 'esp1_Light'
  unit_of_measurement: '%'
  expire_after: 180

- platform: mqtt
  state_topic: !secret mqtt_topic_esp2_temp
  name: 'esp2_Temperature'
  unit_of_measurement: 'ºC'
  expire_after: 180
- platform: mqtt
  state_topic: !secret mqtt_topic_esp2_hum
  name: 'esp2_Humidity'
  unit_of_measurement: '%'
  expire_after: 180
- platform: mqtt
  state_topic: !secret mqtt_topic_esp2_pres
  name: 'esp2_Pressure'
  unit_of_measurement: 'mb'
  expire_after: 180
- platform: mqtt
  state_topic: !secret mqtt_topic_esp2_light_analog
  name: 'esp2_Light'
  unit_of_measurement: '%'
  expire_after: 180

- platform: mqtt
  state_topic: "owntracks/hass/iphone"
  name: 'Batería iPhone 6s'
  unit_of_measurement: '%'
  value_template: '{{ value_json.batt }}'
  expire_after: 3600
- platform: mqtt
  state_topic: "owntracks/hass/iphonese"
  name: 'Batería iPhone SE'
  unit_of_measurement: '%'
  value_template: '{{ value_json.batt }}'
  expire_after: 3600

- platform: enerweb
  name: Galería
  host: !secret host_galeria
  mysql_user: !secret galeria_mysql_user
  mysql_password: !secret galeria_mysql_password
  round: 1
  sensors:
    - ds18b20:
        0000071d270e: Retorno calefacción
        031504c1eeff: Impulsión calefacción
        03150492d7ff: ACS
#    - rpi2:
#        rpit: RPI CPU temp
    - dht22:
        temp: Temperature
        hum: Humidity

- platform: dummy
  sensors:
    humidity_rpi2h:
      friendly_name: Humedad SenseHat
      unit_of_measurement: '%'
    pressure_rpi2h:
      friendly_name: Presión
      unit_of_measurement: 'mb'
    temperature_rpi2h:
      friendly_name: Temperatura SenseHat
      unit_of_measurement: '°C'
    temperatura_estudio_rpi2h:
      friendly_name: Temperatura (DS)
      unit_of_measurement: '°C'
    dht22_temperature_rpi2h:
      friendly_name: Temperatura (DHT)
      unit_of_measurement: '°C'
    dht22_humidity_rpi2h:
      friendly_name: Humedad
      unit_of_measurement: '%'

    temperatura_dormitorio_rpi2mpd:
      friendly_name: Temperatura
      unit_of_measurement: '°C'
    humedad_dormitorio_rpi2mpd:
      friendly_name: Humedad
      unit_of_measurement: '%'
    presion_dormitorio_rpi2mpd:
      friendly_name: Presión
      unit_of_measurement: 'mb'

# Weather sensors:
- platform: myopenweathermap
  api_key: !secret openweathermap_api_key
  forecast: 1
  name: Villena
  scan_interval: 120
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - humidity
    - pressure
    - clouds
    - rain

- platform: yr
  name: Wheather type

# Host & network sensors:
- platform: systemmonitor
  name: RPI Host
  scan_interval: 30
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: last_boot

- platform: command_line
  name: HASS CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 60
#- platform: command_line
#  name: enerPI CPU Temperature
#  command: !secret ssh_cmd_rpi_temp_enerpi
#  unit_of_measurement: "°C"
#  value_template: '{{ value | multiply(0.001) | round(1) }}'
- platform: command_line
  name: KODI CPU Temperature
  command: !secret ssh_cmd_rpi_temp_kodi
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 60
- platform: command_line
  name: influxDB CPU Temperature
  command: !secret ssh_cmd_rpi_temp_influxdb
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 60

- platform: speedtest
  minute:
    - 5
    - 35
  monitored_conditions:
    - ping
    - download
    - upload

- platform: template
  sensors:
    alarm_clock_hour:
      value_template: '{{ states("input_slider.alarm_clock_hour") | round(0) }}'
    alarm_clock_minute:
      value_template: '{{ states("input_slider.alarm_clock_minute") | round(0) }}'
    alarm_clock_time:
      value_template: '{{ states("sensor.alarm_clock_hour") }}:{% if states("sensor.alarm_clock_minute")|length == 1 %}0{% endif %}{{ states("sensor.alarm_clock_minute") }}'

- platform: command_line
  name: CORE Error counter
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh"

- platform: command_line
  name: Error counter (notifiers)
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh"

- platform: command_line
  name: Warning counter (core)
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh core_warning"

- platform: command_line
  name: IP externa
#  command: python3 -c "import requests; print(requests.get('http://remote-host/sensor_data.txt').text)"
  command: cat /home/homeassistant/.homeassistant/external_ip.txt
