# RPI hardware-present sensors:
- platform: myonewire
  names:
    28-8000000152ed: T_Salón
  scan_interval: 30
  maximum: 45
  minimum: 5

- platform: dht
  sensor: DHT22
  pin: 22
  name: Salón
  scan_interval: 30
  monitored_conditions:
    - temperature
    - humidity

- platform: mqtt
  state_topic: "sensor/hum_a020a605b007"
  name: 'esp1_Humidity'
  unit_of_measurement: '%'
  expire_after: 600

- platform: mqtt
  state_topic: "sensor/temp_a020a605b007"
  name: 'esp1_Temperature'
  unit_of_measurement: 'ºC'
  expire_after: 600

- platform: mqtt
  state_topic: "owntracks/hass/iphone"
  name: 'Batería iPhone 6s'
  unit_of_measurement: '%'
  value_template: '{{ value_json.batt }}'
  expire_after: 3600

- platform: mqtt
  state_topic: "owntracks/hass/iphonese"
  name: 'Batería iPhone SE'
  unit_of_measurement: '%'
  value_template: '{{ value_json.batt }}'
  expire_after: 3600

- platform: enerweb
  name: Galería
  host: !secret host_galeria
  mysql_user: !secret galeria_mysql_user
  mysql_password: !secret galeria_mysql_password
  round: 1
  sensors:
    - ds18b20:
        0000071d270e: Retorno calefacción
        031504c1eeff: Impulsión calefacción
        03150492d7ff: ACS
#    - rpi2:
#        rpit: RPI CPU temp
    - dht22:
        temp: Temperature
        hum: Humidity

- platform: dummy
  sensors:
    humidity_rpi2h:
      friendly_name: Humedad SenseHat
      unit_of_measurement: '%'
    pressure_rpi2h:
      friendly_name: Presión SenseHat
      unit_of_measurement: 'mb'
    temperature_rpi2h:
      friendly_name: Temperatura SenseHat
      unit_of_measurement: '°C'
    temperatura_estudio_rpi2h:
      friendly_name: Temperatura estudio
      unit_of_measurement: '°C'
    dht22_temperature_rpi2h:
      friendly_name: Temperatura estudio dht
      unit_of_measurement: '°C'
    dht22_humidity_rpi2h:
      friendly_name: Humedad estudio dht
      unit_of_measurement: '%'
    temperatura_dormitorio_rpi2mpd:
      friendly_name: Temperatura Dormitorio
      unit_of_measurement: '°C'
    dht22_dormitorio_temperature_rpi2mpd:
      friendly_name: Temperatura Dormitorio (dht22)
      unit_of_measurement: '°C'
    dht22_dormitorio_humidity_rpi2mpd:
      friendly_name: Humedad Dormitorio
      unit_of_measurement: '%'

# Weather sensors:
- platform: openweathermap
  api_key: !secret openweathermap_api_key
  forecast: 1
  name: Villena
  scan_interval: 120
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - humidity
    - pressure
    - clouds
    - rain

- platform: yr
  name: Wheather type

# Host & network sensors:
- platform: systemmonitor
  name: RPI Host
  scan_interval: 30
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: last_boot

- platform: speedtest
  minute:
    - 5
    - 35
  monitored_conditions:
    - ping
    - download
    - upload

- platform: template
  sensors:
    alarm_clock_hour:
      value_template: '{{ states("input_slider.alarm_clock_hour") | round(0) }}'
    alarm_clock_minute:
      value_template: '{{ states("input_slider.alarm_clock_minute") | round(0) }}'
    alarm_clock_time:
      value_template: '{{ states("sensor.alarm_clock_hour") }}:{% if states("sensor.alarm_clock_minute")|length == 1 %}0{% endif %}{{ states("sensor.alarm_clock_minute") }}'

- platform: command_line
  name: CORE Error counter
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh"

- platform: command_line
  name: Error counter (notifiers)
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh"

- platform: command_line
  name: Warning counter (core)
  command: "/home/homeassistant/.homeassistant/shell/check_notifiers.sh core_warning"

- platform: command_line
  name: IP externa
#  command: python3 -c "import requests; print(requests.get('http://remote-host/sensor_data.txt').text)"
  command: cat /home/homeassistant/.homeassistant/external_ip.txt
