# RPI hardware-present sensors:
- platform: myonewire
  names:
#    28-800000015326: T_Salón
    28-8000000152ed: T_Salón
  scan_interval: 30
  maximum: 45
  minimum: 5

- platform: dht
  sensor: DHT22
  pin: 22
  name: Salón
  scan_interval: 30
  monitored_conditions:
    - temperature
    - humidity

- platform: enerweb
  name: Galería
  host: !secret host_galeria
  mysql_user: !secret galeria_mysql_user
  mysql_password: !secret galeria_mysql_password
  scan_interval: 45
  round: 1
  sensors:
    - ds18b20:
        0000071d270e: Retorno calefacción
        031504c1eeff: Impulsión calefacción
        03150492d7ff: ACS
    - rpi2:
        rpit: RPI CPU temp
    - dht22:
        temp: Temperature
        hum: Humidity

# Weather sensors:
- platform: openweathermap
  api_key: !secret openweathermap_api_key
  forecast: 1
  name: Villena
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - humidity
    - pressure
    - clouds
    - rain

- platform: yr
  name: Wheather type

# Host & network sensors:
- platform: systemmonitor
  name: RPI Host
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: last_boot

- platform: speedtest
  minute:
    - 5
    - 35
  monitored_conditions:
    - ping
    - download
    - upload

- platform: template
  sensors:
    alarm_clock_hour:
      value_template: '{{ states("input_slider.alarm_clock_hour") | round(0) }}'
    alarm_clock_minute:
      value_template: '{{ states("input_slider.alarm_clock_minute") | round(0) }}'
    alarm_clock_time:
      value_template: '{{ states("sensor.alarm_clock_hour") }}:{% if states("sensor.alarm_clock_minute")|length == 1 %}0{% endif %}{{ states("sensor.alarm_clock_minute") }}'

- platform: command_line
  name: badlogin
  command: '/bin/grep -c invalidpassword /home/homeassistant/.homeassistant/home-assistant.log'

# Stats sensors:
#- platform: statistics
#  entity_id: sensor.enerpi_power
#  name: Power stats
#  sampling_size: 24

#- platform: statistics
#  entity_id: sensor.t_salon
#  name: Temp stats
#  sampling_size: 10

#- platform: statistics
#  entity_id: binary_sensor.pir_salon
#  name: Mov nº
