- alias: Set Hyperion config with 4 Hue lights
  trigger:
    platform: state
    entity_id: input_select.salon_movie_mode
    to: "Ambilight Day (4)"
  action:
    service: shell_command.hyperion_set_config_hue4

- alias: Set Hyperion config with 6 Hue lights
  trigger:
    platform: state
    entity_id: input_select.salon_movie_mode
    to: "Ambilight Night (6)"
  action:
    service: shell_command.hyperion_set_config_hue6

- alias: Set Hyperion OFF
  trigger:
    platform: state
    entity_id: input_select.salon_movie_mode
    to: "Normal"
  action:
    service: switch.turn_off
    entity_id: switch.toggle_kodi_ambilight