- alias: Encendido de TV si apagada y KODI play
  trigger:
    platform: state
    entity_id: media_player.kodi_tv
    from: 'off'
    to: 'playing'
  action:
  - service: media_player.turn_on
    entity_id: media_player.kodi
  - service: telegram_bot.send_message
    data_template:
      title: '*TV ON*'
      target: '{{ states.sensor.telegram_default_chatid.state | int }}'
      message: 'Encendido de TV automático en Kodi PLAY'
      disable_notification: true
      inline_keyboard:
        - TV OFF:/service_call media_player.turn_off media_player.kodi, TV ON:/service_call media_player.turn_on media_player.kodi, ◼︎:/service_call media_player.media_stop media_player.kodi
        - Luces salón:/service_call light.toggle group.luces_salon, +:/init
#
- alias: Apagado de TV si encendida y KODI en idle > 10 min
  trigger:
    platform: state
    entity_id: media_player.kodi_tv
    to: 'idle'
    for:
      minutes: 10
  action:
  - service: media_player.turn_off
    entity_id: media_player.kodi_tv
  - service: telegram_bot.send_message
    data_template:
      title: '*TV OFF*'
      target: '{{ states.sensor.telegram_default_chatid.state | int }}'
      message: 'Apagado de TV automático (Kodi en `idle` > 10 min)'
      disable_notification: true
      inline_keyboard:
        - TV OFF:/service_call media_player.turn_off media_player.kodi, TV ON:/service_call media_player.turn_on media_player.kodi, ◼︎:/service_call media_player.media_stop media_player.kodi
        - Luces salón:/service_call light.toggle group.luces_salon, +:/init

- alias: Apagado de CAM salón en Kodi PLAY nocturno
  trigger:
    platform: state
    entity_id: media_player.kodi
#    from: 'idle'
    to: 'playing'
  condition:
    - condition: sun
      after: sunset
      after_offset: "-0:30:00"
    - condition: state
      entity_id: switch.camara
      state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.camara
  - service: telegram_bot.send_message
    data_template:
      title: '*CAM Salón OFF*'
      target: '{{ states.sensor.telegram_default_chatid.state | int }}'
      message: 'Apagado de cámara de Salón en Kodi PLAY nocturno.'
      disable_notification: true
      inline_keyboard:
        - CAM OFF:/service_call switch.turn_off switch.camara, CAM ON:/service_call switch.turn_on switch.camara, +:/init

- alias: Encendido automático de CAM salón
  trigger:
    platform: state
    entity_id: media_player.kodi_tv
    to: 'off'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: switch.camara
      state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.camara
