# Sun notifications
#- alias: Notify sunrise
#  trigger:
#    platform: sun
#    event: sunrise
#    offset: '+00:00:00'
#  action:
#    service: notify.ios
#    data:
#      title: 'Buenos días!'
#      message: 'Empieza un nuevo día!'
#      data:
#        push:
#          badge: 0
#          sound: "US-EN-Morgan-Freeman-Good-Morning.wav"
#          category: "ALARM" # Needs to match the top level identifier you used in the ios configuration

- alias: Notify sunset
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'
  action:
    service: notify.ios
    data:
      title: 'Empieza la noche!'
      message: 'Acaba de ponerse el sol..'
      data:
        push:
          badge: 0
          sound: "US-EN-Morgan-Freeman-Setting-The-Mood.wav"
          category: "CONFIRM" # Needs to match the top level identifier you used in the ios configuration
