# enerPI POWER notifications - TODO refinar valores y contenido de notificación (+svg?)
- alias: Maxpower
  trigger:
    platform: template
    value_template: "{% if (states('sensor.enerpi_power')|float / 1000 > states.input_slider.enerpi_max_power.state|float) %}true{% else %}false{% endif %}"

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.switch_control_enerpi_max_power
        state: 'on'
      - condition: state
        entity_id: input_boolean.state_enerpi_alarm_max_power
        state: 'off'
        for:
          seconds: 30
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.state_enerpi_alarm_max_power
  - service: notify.ios
    data_template:
      title: "Alto consumo eléctrico!"
      message: "Potencia actual: {{ states.sensor.enerpi_power.state }} W. Ojo con los cortes de ICP por exceso..."
      data:
        push:
          badge: '{{ states.sensor.enerpi_power.state }}'
          sound: "US-EN-Morgan-Freeman-Vacate-The-Premises.wav"
          category: "ALARM" # Needs to match the top level identifier you used in the ios configuration

- alias: MaxpowerOff
  trigger:
    platform: template
    value_template: >
        {{ states('sensor.enerpi_power')|float / 1000 < states.input_slider.enerpi_max_power_reset.state|float }}
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.switch_control_enerpi_max_power
        state: 'on'
      - condition: state
        entity_id: input_boolean.state_enerpi_alarm_max_power
        state: 'on'
        for:
          minutes: 1
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.state_enerpi_alarm_max_power
  - service: notify.ios
    data_template:
      title: "Consumo eléctrico: Normal"
      message: "Potencia eléctrica actual: {{ states.sensor.enerpi_power.state }} W. Ya no hay peligro de corte por sobre-consumo."

