# Set a light scene with a python_script
- alias: Salón Select Scene
  trigger:
    platform: state
    entity_id: input_select.salon_light_scene
  action:
    - service: python_script.select_light_profile
      data_template:
        scene: '{{ trigger.to_state.state }}'