# Startup notifications, default states, and more to run at HA start
- alias: Start HomeAssistant
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: python_script.set_telegram_chatid_sensor
      data:
        chat_id: !secret telegram_bot_chat_id_admin
    - delay:
        seconds: 5
    - service: python_script.start_states
      data:
        expert_mode_state: off  # Start without expert mode
    - delay:
        seconds: 30
    - service: shell_command.restart_homebridge
    #  - service: notify.ios
    #    data:
    #      title: "Homebridge re-started"
    #      message: "Now you can reload the HomeKit info from HA."
    #      target: !secret ios_target
    #      data:
    #        push:
    #          category: "CONFIRM"

# New version notify
- alias: Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
  - service: notify.ios_iphone
    data:
      title: 'New Home Assistant Release'
      message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
      data:
        push:
          badge: 1
          category: "CONFIRM"

# Flush MySQL database if not ok & notify:
- alias: Database flush
  trigger:
    platform: state
    entity_id: binary_sensor.database_ok
    to: 'off'
    for:
      minutes: 2
  action:
    - service: telegram_bot.send_message
      data:
        title: '*MySQL flush*'
        target: !secret telegram_bot_chat_id_admin
        message: !secret msg_recorder_flush
        disable_notification: false
        disable_web_page_preview: true
    - delay:
        seconds: 5
    - service: shell_command.cmd_recorder_flush_hosts
