# Startup notifications, default states, and more to run at HA start
- alias: Start HomeAssistant
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay:
        seconds: 5
    - service: python_script.start_states
      data:
        # Start without expert mode
        expert_mode_state: off
    - delay:
        seconds: 30
    - service: script.restart_homebridge

# New version notify
- alias: Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
  - service: notify.ios_iphone
    data:
      title: 'New Home Assistant Release'
      message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
      data:
        push:
          badge: 1
          category: "CONFIRM"

# Flush MySQL database if not ok & notify:
- alias: Database flush
  trigger:
    platform: state
    entity_id: binary_sensor.database_ok
    to: 'off'
    for:
      minutes: 2
  action:
    - service: telegram_bot.send_message
      data:
        title: '*MySQL flush*'
        target: !secret telegram_bot_chat_id_admin
        message: !secret msg_recorder_flush
        disable_notification: false
        disable_web_page_preview: true
    - delay:
        seconds: 5
    - service: shell_command.cmd_recorder_flush_hosts
