# Modo 'experto' (con visibilidad extra / normal)
# switch groups visibility:
- alias: Visibilidad modo experto ON/OFF
  trigger:
    platform: state
    entity_id: input_boolean.show_expert_mode
  action:
    - service: python_script.change_expert_mode_view
      data_template:
        expert_mode_state: '{{ trigger.to_state.state }}'

