# switch groups visibility:
# Expert mode:
# group.salon,group.estudio_rpi2h,group.dormitorio_rpi2mpd,group.cocina,group.caldera,group.links,group.cacharros,group.hass_control,group.tiempo_en_villena,group.enerpi_max_power_control,group.scripts,group.host_rpi3,group.host_rpi2_hat,group.host_rpi2_mpd,group.conectivity
# Normal mode:
# group.salon_simple,group.estudio_rpi2h_simple,group.dormitorio_rpi2mpd_simple,group.cocina_simple,group.caldera_simple,group.links_simple,group.cacharros_simple,group.hass_control_simple,group.tiempo_en_villena_simple

# Modo 'experto' (con visibilidad extra)
- alias: Visibilidad modo experto ON
  trigger:
    platform: state
    entity_id: input_boolean.show_expert_mode
    to: 'on'
  action:
    - service: group.set_visibility
      entity_id: group.salon_simple,group.estudio_rpi2h_simple,group.dormitorio_rpi2mpd_simple,group.cocina_simple,group.caldera_simple,group.links_simple,group.cacharros_simple,group.hass_control_simple,group.tiempo_en_villena_simple
      data:
        visible: False
    - service: group.set_visibility
      entity_id: group.salon,group.estudio_rpi2h,group.dormitorio_rpi2mpd,group.cocina,group.caldera,group.links,group.cacharros,group.hass_control,group.tiempo_en_villena,group.enerpi_max_power_control,group.scripts,group.host_rpi3,group.host_rpi2_hat,group.host_rpi2_mpd,group.conectivity
      data:
        visible: True

- alias: Visibilidad modo experto OFF
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.show_expert_mode
      to: 'off'
  action:
    - service: group.set_visibility
      entity_id: group.salon_simple,group.estudio_rpi2h_simple,group.dormitorio_rpi2mpd_simple,group.cocina_simple,group.caldera_simple,group.links_simple,group.cacharros_simple,group.hass_control_simple,group.tiempo_en_villena_simple
      data:
        visible: True
    - service: group.set_visibility
      entity_id: group.salon,group.estudio_rpi2h,group.dormitorio_rpi2mpd,group.cocina,group.caldera,group.links,group.cacharros,group.hass_control,group.tiempo_en_villena,group.enerpi_max_power_control,group.scripts,group.host_rpi3,group.host_rpi2_hat,group.host_rpi2_mpd,group.conectivity
      data:
        visible: False
