# Slave HASS in RPI2 - Bedroom
homeassistant:
  customize:
    binary_sensor.pir_dormitorio_rpi2mpd:
      friendly_name: Movimiento (dormitorio)
      device_class: motion
      homebridge_hidden: true
    sensor.ram_free_rpi2mpd:
      homebridge_hidden: True
    sensor.cpu_use_rpi2mpd:
      homebridge_hidden: True
    sensor.disk_use__rpi2mpd:
      homebridge_hidden: True
    sensor.hass_cpu_temperature_rpi2mpd:
      homebridge_hidden: True

    sensor.dormitorio_light_level_rpi2mpd:
      homebridge_sensor_type: light

    sensor.dormitorio_temperature_rpi2mpd:
      homebridge_hidden: True
    sensor.dormitorio_humidity_rpi2mpd:
      homebridge_hidden: True
#      homebridge_sensor_type: humidity

    sensor.dormitorio_htu21d_humidity_rpi2mpd:
      homebridge_sensor_type: humidity

    media_player.dormitorio_mopidy:
      homebridge_hidden: True

binary_sensor:
  - platform: dummy
    sensors:
      pir_dormitorio_rpi2mpd:
        friendly_name: Movimiento en Dormitorio
        device_class: motion

sensor:
  - platform: dummy
    sensors:
      dormitorio_temperature_rpi2mpd:
        friendly_name: Temperatura
        unit_of_measurement: '째C'
      dormitorio_humidity_rpi2mpd:
        friendly_name: Humedad
        unit_of_measurement: '%'
      dormitorio_pressure_rpi2mpd:
        friendly_name: Presi처n
        unit_of_measurement: 'mb'
      dormitorio_light_level_rpi2mpd:
        friendly_name: Iluminaci처n
        unit_of_measurement: 'lx'
      dormitorio_htu21d_temperature_rpi2mpd:
        friendly_name: Temperatura HTU
        unit_of_measurement: '째C'
      dormitorio_htu21d_humidity_rpi2mpd:
        friendly_name: Humedad HTU
        unit_of_measurement: '%'

media_player:
  - platform: mpd
    host: !secret mpd_host
    port: !secret mpd_port
    name: Dormitorio (Mopidy)
  #  scan_interval: 60

group:
  Dormitorio RPI2MPD:
    name: Dormitorio
    control: hidden
    entities:
      - sensor.dormitorio_temperature_rpi2mpd
      - sensor.dormitorio_humidity_rpi2mpd
      - sensor.dormitorio_pressure_rpi2mpd
      - sensor.dormitorio_htu21d_temperature_rpi2mpd
      - sensor.dormitorio_htu21d_humidity_rpi2mpd
      - sensor.dormitorio_light_level_rpi2mpd
      - binary_sensor.pir_dormitorio_rpi2mpd
      - switch.altavoz
      - switch.calefactor

  Dormitorio RPI2MPD_simple:
    name: Dormitorio
    control: hidden
    entities:
      - sensor.dormitorio_htu21d_temperature_rpi2mpd
      - sensor.dormitorio_htu21d_humidity_rpi2mpd
#      - sensor.dormitorio_temperature_rpi2mpd
#      - sensor.dormitorio_humidity_rpi2mpd
#      - sensor.dormitorio_pressure_rpi2mpd
      - sensor.dormitorio_light_level_rpi2mpd
      - switch.altavoz
      - switch.calefactor

  Host Dormitorio:
    - sensor.hass_cpu_temperature_rpi2mpd
    - sensor.cpu_use_rpi2mpd
    - sensor.ram_free_rpi2mpd
    - sensor.last_boot_rpi2mpd
    - sensor.disk_use__rpi2mpd
