# HUE LIGHTS
homeassistant:
  customize:
    input_number.light_main_slider_salon:
      friendly_name: Brillo
      icon: mdi:brightness-7
    input_number.light_temp_slider_salon:
      friendly_name: Temperatura de color
      icon: mdi:temperature-kelvin
    automation.brillo_salon_sync:
      icon: mdi:brightness-auto
      homebridge_hidden: true
      friendly_name: Sync brillo bola grande

    light.bola_grande:
      icon: mdi:ceiling-light
    light.bola_pequena:
      icon: mdi:ceiling-light
    light.hue_habitacion:
      icon: mdi:ceiling-light
    light.aura_habitacion:
      icon: mdi:lava-lamp
    light.pie_tv:
      icon: mdi:lamp
    light.pie_sofa:
      icon: mdi:lamp
    light.cuenco:
      icon: mdi:lava-lamp
    light.lamparita:
      icon: mdi:lava-lamp
    light.flexo:
      icon: mdi:lightbulb-outline
    light.central:
      icon: mdi:ceiling-light

light:
  - platform: hue
    host: 192.168.1.45
    allow_unreachable: true
    homebridge_hidden: true
    scan_interval: 12

#hue:

sensor:
- platform: hue
  devices:
   - RWL
#   - GEO

input_number:
  # Master Sliders Salón (brillo y Tª color)
  light_main_slider_salon:
    name: Brillo salón
  #  initial: 0
    min: 0
    max: 255
    step: 1
  light_temp_slider_salon:
    name: Blanco Salón
  #  initial: 10
    min: 0
    max: 100
    step: 1

input_select:
  salon_light_scene:
    name: Escena de luz
    options:
     - Concentración
     - Energía
     - Relax
     - Lectura
     - 'OFF'
    initial: Energía
    icon: mdi:lightbulb

  #salon_movie_mode:
  #  name: Modo ambient TV
  #  options:
  #   - Normal
  #   - Ambilight Day (4)
  #   - Ambilight Night (6)
  #  initial: Normal
  #  icon: mdi:traffic-light

automation:
- alias: Turn ON TV with lights (hue switch)
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch
    to: '1_hold'
  action:
    - service: script.play_kodi_pvr
    - event: flash_light
      event_data:
        color: orange
        persistence: 2
        flashes: 3

- alias: Turn OFF all (hue switch)
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch
    to: '4_hold'
  action:
    - service: media_player.turn_off
      entity_id: media_player.kodi
    - event: flash_light
      event_data:
        color: red
        persistence: 1
        flashes: 2
    - delay:
        seconds: 5
    - service: homeassistant.turn_off
      entity_id: group.all_lights,switch.cocina,switch.estudio_light_relay
    - service: telegram_bot.send_message
      data_template:
        title: '*All Off*'
        message: "Apagando TV y luces al mantener pulsado OFF en mando hue"
        target: '{{ states.sensor.telegram_default_chatid.state | int }}'
        disable_notification: true
        inline_keyboard:
          - TV OFF:/service_call media_player.turn_off media_player.kodi, TV ON:/service_call media_player.turn_on media_player.kodi
          - Aura habitación:/service_call light.toggle light.aura_habitacion

- alias: Turn Cinema mode ON (hue switch)
  trigger:
    platform: state
    entity_id: sensor.hue_dimmer_switch
    to: '3_hold'
  action:
    - service: media_player.turn_on
      entity_id: media_player.kodi
    - event: flash_light
      event_data:
        color: blue
        persistence: 2
        flashes: 3
    - delay:
        seconds: 5
    - service: script.update_library
    - service: switch.turn_on
      entity_id: switch.toggle_kodi_ambilight
    - service: telegram_bot.send_message
      data_template:
        title: '*Cinema mode ON*'
        message: ""
        target: '{{ states.sensor.telegram_default_chatid.state | int }}'
        disable_notification: true
        inline_keyboard:
          - Ambilight:/service_call switch.toggle switch.toggle_kodi_ambilight, Luces:/service_call light.toggle light.salon

group:
  Master luces del salón:
    - input_number.light_main_slider_salon
    - input_number.light_temp_slider_salon
    - input_select.salon_light_scene

  Luces Estudio:
#    control: hidden
    entities:
      - switch.estudio_light_relay
      - light.flexo

  Luces Salón:
    - light.bola_grande
    - light.bola_pequena
    - light.central
    - light.pie_tv
    - light.pie_sofa
    - light.cuenco
    - light.lamparita

  Luces Dormitorio:
    - light.aura_habitacion
    - light.hue_habitacion

#  Hue sensors:
#    - sensor.hue_dimmer_switch
#    - sensor.iphone
