# Kitchen ESP8266 module (MQTT connected):
homeassistant:
  customize:
    sensor.esp1_humidity:
      friendly_name: Humedad
      icon: mdi:water-percent
    #  homebridge_hidden: true
    sensor.esp1_temperature:
      friendly_name: Temperatura
      icon: mdi:thermometer
    #  homebridge_hidden: true
    sensor.esp1_light:
      friendly_name: Iluminación
      homebridge_hidden: true
      icon: mdi:lightbulb-on
    switch.use_esp1_leds:
      friendly_name: Usar LEDs
      icon: mdi:led-outline
      homebridge_hidden: true
    switch.use_esp1_binary_sensors:
      friendly_name: Usar sensores binarios
      icon: mdi:camera-burst
      homebridge_hidden: true
    binary_sensor.esp1_pir:
      friendly_name: Movimiento (cocina)
      homebridge_hidden: true
#    binary_sensor.esp1_vibro:
#      friendly_name: Vibración (cocina)
#      homebridge_hidden: true
#    binary_sensor.esp1_light:
#      friendly_name: Luz (cocina)
#      homebridge_hidden: true
    binary_sensor.cocina_online:
      homebridge_hidden: true

binary_sensor:
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp1_pir
    name: esp1_PIR
  #  qos (Optional): The maximum QoS level of the state topic. Default is 0.
    payload_on: "on"
    payload_off: "off"
    device_class: motion
  #- platform: mqtt
  #  state_topic: !secret mqtt_topic_esp1_vibro
  #  name: esp1_Vibro
  ##  qos (Optional): The maximum QoS level of the state topic. Default is 0.
  #  payload_on: "on"
  #  payload_off: "off"
  #  device_class: vibration
  #- platform: mqtt
  #  state_topic: !secret mqtt_topic_esp1_light
  #  name: esp1_Light
  ##  qos (Optional): The maximum QoS level of the state topic. Default is 0.
  #  payload_on: "on"
  #  payload_off: "off"
  #  device_class: light
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp1_online
    name: Cocina Online
  #  qos (Optional): The maximum QoS level of the state topic. Default is 0.
    payload_on: "on"
    payload_off: "off"
    device_class: connectivity

sensor:
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp1_hum
    name: 'esp1_Humidity'
    unit_of_measurement: '%'
    expire_after: 180
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp1_temp
    name: 'esp1_Temperature'
    unit_of_measurement: 'ºC'
    expire_after: 180
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp1_light_analog
    name: 'esp1_Light'
    unit_of_measurement: '%'
    expire_after: 180

switch:
  - platform: mqtt
    name: use_esp1_binary_sensors
    command_topic: !secret mqtt_topic_esp1_switch_binary_sensors_set
    state_topic: !secret mqtt_topic_esp1_switch_binary_sensors_state
    payload_on: 'on'
    payload_off: 'off'
    retain: true
  - platform: mqtt
    name: use_esp1_leds
    command_topic: !secret mqtt_topic_esp1_switch_leds_set
    state_topic: !secret mqtt_topic_esp1_switch_leds_state
    payload_on: 'on'
    payload_off: 'off'
    retain: true

group:
  Cocina:
    name: Cocina
    control: hidden
    entities:
      - binary_sensor.cocina_online
      - sensor.esp1_temperature
      - sensor.esp1_humidity
      - sensor.esp1_light
      - switch.use_esp1_leds
      - switch.use_esp1_binary_sensors
      - binary_sensor.esp1_pir
  #    - binary_sensor.esp1_light
  #    - binary_sensor.esp1_vibro
      # From rf outlets
      - switch.cocina

  Cocina_simple:
    name: Cocina
    control: hidden
    entities:
      - sensor.esp1_temperature
      - sensor.esp1_humidity
      - sensor.esp1_light
      # From rf outlets
      - switch.cocina

automation:
- alias: Encendido LED Cocina
  trigger:
    platform: state
    entity_id: binary_sensor.esp1_pir
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: state
        entity_id: switch.cocina
        state: 'off'
      - condition: template
        value_template: '{{ states.sensor.esp1_light.state |float < 75 }}'
  action:
    - service: switch.turn_on
      entity_id: switch.cocina

- alias: Apagado LED Cocina
  trigger:
    platform: state
    entity_id: binary_sensor.esp1_pir
    state: 'off'
    for:
      minutes: 3
  condition:
    condition: state
    entity_id: switch.cocina
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.cocina
