homeassistant:
  customize:
    # Local sensors
    sensor.T_salon:
      friendly_name: Temperatura (DS)
      homebridge_hidden: True
    #  homebridge_name: Temperatura (DS)
    sensor.salon_temperature:
      friendly_name: Temperatura
    sensor.salon_humidity:
      friendly_name: Humedad
      icon: mdi:water-percent
      homebridge_sensor_type: humidity
    sensor.salon_pressure:
      friendly_name: Presión
      icon: mdi:weather-cloudy

    sensor.salon_light_level:
      friendly_name: Iluminación
      icon: mdi:lightbulb
      device_class: light

    binary_sensor.pir_salon:
      friendly_name: Movimiento (salón)
      device_class: motion
      homebridge_hidden: true

    # Openweather sensors
    sensor.villena_temperature:
      friendly_name: Temperatura exterior
    sensor.villena_wind_speed:
      friendly_name: Velocidad del viento
      homebridge_hidden: True
      icon: mdi:weather-windy
    sensor.villena_humidity:
      friendly_name: Humedad exterior
      icon: mdi:water-percent
    sensor.villena_pressure:
      friendly_name: Presión
      homebridge_hidden: True
      icon: mdi:weather-windy-variant
    sensor.villena_condition:
      friendly_name: Condición general
      homebridge_hidden: True
    sensor.villena_cloud_coverage:
      friendly_name: Nubes
      homebridge_hidden: True
      icon: mdi:weather-cloudy
    sensor.villena_rain:
      friendly_name: LLuvia
      homebridge_hidden: True
      icon: mdi:weather-rainy
    sensor.villena_forecast:
      friendly_name: Previsión
      homebridge_hidden: True

    sensor.yw_day1_condition:
      friendly_name: Mañana
      homebridge_hidden: True
    sensor.yw_day1_temperature_min:
      friendly_name: Mínima mañana
      homebridge_hidden: True
    sensor.yw_day1_temperature_max:
      friendly_name: Máxima mañana
      homebridge_hidden: True
    sensor.yw_day2_condition:
      friendly_name: Pasado mañana
      homebridge_hidden: True
    sensor.yw_day2_temperature_min:
      friendly_name: Mínima pasado mañana
      homebridge_hidden: True
    sensor.yw_day2_temperature_max:
      friendly_name: Máxima pasado mañana
      homebridge_hidden: True

camera:
  # RPI Camera
  - platform: rpi_camera
    name: PiCamera Salón
    image_width: 1024
    image_height: 768
    image_quality: 70
    image_rotation: 180
    timelapse: 1000
  #  horizontal_flip: 1
  #  vertical_flip: 0
    file_path: /home/homeassistant/picamera/image.jpg

binary_sensor:
  - platform: rpi_gpio
    name: Movimiento Salón
    device_class: motion
    ports:
      18: PIR Salón
    bouncetime: 50
    pull_mode: "UP"
  #  invert_logic: true

sensor:
  # RPI hardware-present sensors:
  - platform: myonewire
    names:
      28-8000000152ed: T_Salón
    scan_interval: 30
    maximum: 45
    minimum: 5

  # BH1750 in RPI
  - platform: bh1750
    name: salon_light_level
    operation_mode: continuous_high_res_mode_2
    measurement_delay_ms: 10
    sensibility: 125
    multiplier: 1.5
    scan_interval: 30

  # BME280 in RPI
  - platform: bme280
    name: salon
    i2c_address: 0x77
    operation_mode: 2  # forced
    time_standby: 5
    oversampling_temperature: 4
    oversampling_pressure: 4
    oversampling_humidity: 4
    delta_temperature: -0.3
    monitored_conditions:
      - temperature
      - humidity
      - pressure
    scan_interval: 30

  - platform: yr
    name: Weather type

# Weather sensors:
  - platform: myopenweathermap
    api_key: !secret openweathermap_api_key
    forecast: 1
    name: Villena
    scan_interval: 180
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - pressure
      - clouds
      - rain

  - platform: yweather
    woeid: !secret yahoo_woeid
    forecast: 1
    name: yw_day1
    monitored_conditions:
      - weather
      - temp_min
      - temp_max
  - platform: yweather
    woeid: !secret yahoo_woeid
    forecast: 2
    name: yw_day2
    monitored_conditions:
      - weather
      - temp_min
      - temp_max

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    name: Local Weather

group:
  Salón:
    control: hidden
    entities:
      - sensor.t_salon
      - sensor.salon_temperature
      - sensor.salon_humidity
      - sensor.salon_pressure
      - sensor.salon_light_level
      - binary_sensor.pir_salon
      - binary_sensor.motioncam_salon
      - switch.camara
      - switch.kodi_tv_salon

  Salón_simple:
    name: Salón
    control: hidden
    entities:
      - sensor.t_salon
      - sensor.salon_temperature
      - sensor.salon_humidity
#      - sensor.salon_pressure
      - sensor.salon_light_level
      - switch.camara
      - switch.kodi_tv_salon

  weather:
    name: !secret weather_location
    entities:
      - sun.sun
      - sensor.villena_temperature
      - sensor.villena_humidity
      - sensor.villena_wind_speed
      - sensor.villena_pressure
      - sensor.villena_condition
      - sensor.villena_cloud_coverage
      - sensor.villena_rain
      - sensor.villena_forecast
      - sensor.yr_symbol

  weather_simple:
    name: !secret weather_location
    entities:
      - sensor.villena_temperature
      - sensor.villena_humidity
      - sensor.villena_cloud_coverage
      - sensor.villena_forecast

  weather_forecast:
    name: Previsión
    entities:
      - weather.local_weather
      - sensor.yw_day1_condition
      - sensor.yw_day1_temperature_min
      - sensor.yw_day1_temperature_max
      - sensor.yw_day2_condition
      - sensor.yw_day2_temperature_min
      - sensor.yw_day2_temperature_max
