# Slave HASS in RPI2 - Office
homeassistant:
  customize:
    switch.estudio_light_relay:
      icon: mdi:ceiling-light

    binary_sensor.estudio_manual_light_switch_rpi2h:
      icon: mdi:toggle-switch
      friendly_name: Conmutador manual

    binary_sensor.pir_estudio_rpi2h:
      friendly_name: Movimiento (estudio)
      device_class: motion
      homebridge_hidden: true
    binary_sensor.vibration_sensor_rpi2h:
      friendly_name: Vibración (estudio)
      device_class: vibration
      homebridge_hidden: true

    sensor.estudio_temperature_rpi2h:
      friendly_name: Temperatura
      unit_of_measurement: '°C'
      icon: mdi:thermometer
    sensor.estudio_humidity_rpi2h:
      friendly_name: Humedad
      unit_of_measurement: '%'
      icon: mdi:water-percent
    sensor.estudio_pressure_rpi2h:
      friendly_name: Presión
      unit_of_measurement: "mb"
      icon: mdi:weather-cloudy
    sensor.estudio_light_level_rpi2h:
      icon: mdi:lightbulb
      homebridge_sensor_type: light
      device_class: light
      friendly_name: Iluminación

    sensor.hass_cpu_temperature_rpi2h:
      friendly_name: HASS CPU Temperature
      homebridge_hidden: true
    sensor.cpu_use_rpi2h:
      icon: mdi:memory
      friendly_name: CPU Use
      homebridge_hidden: true
    sensor.ram_free_rpi2h:
      icon: mdi:memory
      friendly_name: RAM Free
      homebridge_hidden: true
    sensor.last_boot_rpi2h:
      icon: mdi:clock
      friendly_name: Last Boot
      homebridge_hidden: true
    sensor.disk_use__rpi2h:
      icon: mdi:harddisk
      friendly_name: Disk Use /
      homebridge_hidden: true

#binary_sensor.vibration_sensor_raw
#binary_sensor.vibration_sensor

binary_sensor:
  - platform: mqtt
    state_topic: ha_office/binary_sensor/pir_estudio/state
    name: pir_estudio_rpi2h
  #  qos (Optional): The maximum QoS level of the state topic. Default is 0.
    payload_on: "on"
    payload_off: "off"
    device_class: motion
  - platform: mqtt
    state_topic: ha_office/binary_sensor/vibration_sensor/state
#    state_topic: ha_office/binary_sensor/vibration_sensor_raw/state
    name: vibration_sensor_rpi2h
  #  qos (Optional): The maximum QoS level of the state topic. Default is 0.
    payload_on: "on"
    payload_off: "off"
    device_class: vibration

  - platform: mqtt
    state_topic: ha_office/binary_sensor/estudio_manual_light_switch/state
    name: estudio_manual_light_switch_rpi2h
    payload_on: "on"
    payload_off: "off"


sensor:
  - platform: mqtt
    state_topic: ha_office/sensor/estudio_temperature/state
    name: estudio_temperature_rpi2h
    unit_of_measurement: '°C'
    expire_after: 180
  - platform: mqtt
    state_topic: ha_office/sensor/estudio_humidity/state
    name: estudio_humidity_rpi2h
    unit_of_measurement: '%'
    expire_after: 180
  - platform: mqtt
    state_topic: ha_office/sensor/estudio_pressure/state
    name: estudio_pressure_rpi2h
    unit_of_measurement: 'mb'
    expire_after: 180
  - platform: mqtt
    state_topic: ha_office/sensor/estudio_light_level/state
    name: estudio_light_level_rpi2h
    unit_of_measurement: 'lx'
    expire_after: 180

  - platform: mqtt
    state_topic: ha_office/sensor/hass_cpu_temperature/state
    name: hass_cpu_temperature_rpi2h
    unit_of_measurement: '°C'
    expire_after: 180
  - platform: mqtt
    state_topic: ha_office/sensor/cpu_use/state
    name: cpu_use_rpi2h
    unit_of_measurement: '%'
    expire_after: 180
  - platform: mqtt
    state_topic: ha_office/sensor/ram_free/state
    name: ram_free_rpi2h
    unit_of_measurement: 'mb'
    expire_after: 180
  - platform: mqtt
    state_topic: ha_office/sensor/last_boot/state
    name: last_boot_rpi2h
    expire_after: 300
  - platform: mqtt
    state_topic: ha_office/sensor/disk_use_/state
    name: disk_use__rpi2h
    expire_after: 300


switch:
  - platform: command_line
    switches:
      estudio_light_relay:
        command_on: !secret switch_lights_estudio_on
        command_off: !secret switch_lights_estudio_off
        command_state: !secret switch_lights_estudio_status
        value_template: '{{ value_json == 1 }}'
        friendly_name: Luces estudio

automation:
  - alias: Manual toggle lights estudio
    trigger:
      - platform: state
        entity_id: binary_sensor.estudio_manual_light_switch_rpi2h
    condition:
      - condition: template
        value_template: '{{ (trigger.from_state.state == "on") or (trigger.from_state.state == "off") }}'
    action:
      - service: switch.toggle
        entity_id: switch.estudio_light_relay

  - alias: Encendido luces estudio
    trigger:
      platform: state
      entity_id: binary_sensor.pir_estudio_rpi2h
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.family
          state: 'home'
        - condition: state
          entity_id: switch.estudio_light_relay
          state: 'off'
          for:
            seconds: 60
        - condition: state
          entity_id: switch.switch_master_alarm
          state: 'off'
        - condition: template
          value_template: '{{ states.sensor.estudio_light_level_rpi2h.state |int < 20 }}'
#        - condition: or
#          conditions:
#            - condition: time
#              after: '23:00:00'
#              before: '10:00:00'
#            - condition: time
#              after: '20:30:00'
#              before: '0:00:00'
    action:
      - service: switch.turn_on
        entity_id: switch.estudio_light_relay

  - alias: Apagado Luces estudio
    trigger:
      platform: state
      entity_id: binary_sensor.pir_estudio_rpi2h
      to: 'off'
      for:
        minutes: 3
    condition:
      condition: state
      entity_id: switch.estudio_light_relay
      state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.estudio_light_relay

group:
  Estudio RPi2h:
    name: Estudio
    control: hidden
    entities:
      - sensor.estudio_temperature_rpi2h
      - sensor.estudio_humidity_rpi2h
      - sensor.estudio_pressure_rpi2h
      - sensor.estudio_light_level_rpi2h
      - binary_sensor.pir_estudio_rpi2h
      - binary_sensor.motioncam_estudio
      - binary_sensor.vibration_sensor_rpi2h
#      - binary_sensor.estudio_manual_light_switch_rpi2h
      - switch.estudio_light_relay
      - switch.new_switch_2

  Estudio RPi2h_simple:
    name: Estudio
    control: hidden
    entities:
      - sensor.estudio_temperature_rpi2h
      - sensor.estudio_humidity_rpi2h
      - sensor.estudio_pressure_rpi2h
      - sensor.estudio_light_level_rpi2h
      - switch.estudio_light_relay
      - switch.new_switch_2

  Host Estudio:
    control: hidden
    entities:
      - sensor.hass_cpu_temperature_rpi2h
      - sensor.cpu_use_rpi2h
      - sensor.ram_free_rpi2h
      - sensor.last_boot_rpi2h
      - sensor.disk_use__rpi2h
