# Slave HASS in RPI2 - Office
homeassistant:
  customize:
    binary_sensor.pir_estudio_rpi2h:
      friendly_name: Movimiento (estudio)
      device_class: motion
      homebridge_hidden: true
    binary_sensor.vibration_sensor_rpi2h:
      friendly_name: Vibraci처n (estudio)
      device_class: vibration
      homebridge_hidden: true

    binary_sensor.estudio_manual_light_switch_rpi2h:
      homebridge_hidden: true
    switch.estudio_light_relay:
      friendly_name: Luz estudio
      icon: mdi:lightbulb-on

    sensor.ram_free_rpi2h:
      homebridge_hidden: True
    sensor.cpu_use_rpi2h:
      homebridge_hidden: True
    sensor.disk_use__rpi2h:
      homebridge_hidden: True
    sensor.last_boot_rpi2h:
      homebridge_hidden: True

    sensor.hass_cpu_temperature_rpi2h:
      homebridge_hidden: True

binary_sensor:
  - platform: dummy
    sensors:
      pir_estudio_rpi2h:
        friendly_name: Movimiento en Estudio
        device_class: motion
      vibration_sensor_rpi2h:
        friendly_name: Vibraci처n en Estudio
        device_class: vibration

      estudio_manual_light_switch_rpi2h:
        friendly_name: Interruptor manual
        device_class: light

sensor:
  - platform: dummy
    sensors:
      estudio_temperature_rpi2h:
        friendly_name: Temperatura
        unit_of_measurement: '째C'
      estudio_humidity_rpi2h:
        friendly_name: Humedad
        unit_of_measurement: '%'
      estudio_pressure_rpi2h:
        friendly_name: Presi처n
        unit_of_measurement: "mb"

switch:
  - platform: rest
    name: estudio_light_relay
    resource: !secret switch_slave_hass_light_url
    body_on: '{"state": "on"}'
    body_off: '{"state": "off"}'
    is_on_template: '{{value_json.state == "on"}}'

group:
  Estudio RPi2h:
    name: Estudio
    control: hidden
    entities:
      - sensor.estudio_temperature_rpi2h
      - sensor.estudio_humidity_rpi2h
      - sensor.estudio_pressure_rpi2h
      - binary_sensor.pir_estudio_rpi2h
      - binary_sensor.motioncam_estudio
      - binary_sensor.vibration_sensor_rpi2h
      - binary_sensor.estudio_manual_light_switch_rpi2h
      - switch.estudio_light_relay

  Estudio RPi2h_simple:
    name: Estudio
    control: hidden
    entities:
      - sensor.estudio_temperature_rpi2h
      - sensor.estudio_humidity_rpi2h
      - sensor.estudio_pressure_rpi2h

  Host Estudio:
    - sensor.hass_cpu_temperature_rpi2h
    - sensor.cpu_use_rpi2h
    - sensor.ram_free_rpi2h
    - sensor.last_boot_rpi2h
    - sensor.disk_use__rpi2h

