###############################################################################
# KODI - OSMC - Hyperion Control
###############################################################################
homeassistant:
  customize:
    media_player.kodi:
      icon: mdi:kodi
      friendly_name: Kodi OSMC
      homebridge_name: Tele
      homebridge_media_player_switch: on_off
    switch.toggle_kodi_ambilight:
      icon: mdi:monitor-multiple
      homebridge_name: Kodi Ambilight
    switch.toggle_config_kodi_ambilight:
      icon: mdi:traffic-light
      homebridge_hidden: true
    script.play_kodi_pvr:
      friendly_name: Enciende la caja tonta
      icon: mdi:television-guide
    script.restart_kodi_osmc:
      friendly_name: Reset KODI
      icon: mdi:restart

    script.update_library:
      icon: mdi:refresh
    script.stop_kodi:
      icon: mdi:stop
    script.quit_kodi:
      icon: mdi:close
    script.recent_episodes:
      icon: mdi:play-circle
    script.recent_movies:
      icon: mdi:movie
    script.pvr_channels:
      icon: mdi:play-box-outline
    input_select.kodi_results:
      icon: mdi:kodi

switch:
  - platform: command_line
    scan_interval: 120
    switches:
      toggle_kodi_ambilight:
        command_on: '/home/homeassistant/.homeassistant/shell/switch_kodi_hyperion.sh 1'
        command_off: '/home/homeassistant/.homeassistant/shell/switch_kodi_hyperion.sh 0'
        command_state: '/home/homeassistant/.homeassistant/shell/switch_kodi_hyperion.sh'
        friendly_name: KODI Ambilight
        value_template: '{{ value_json == 1 }}'
      toggle_config_kodi_ambilight:
        command_on: '/home/homeassistant/.homeassistant/shell/switch_kodi_hyperion.sh set_hue6'
        command_off: '/home/homeassistant/.homeassistant/shell/switch_kodi_hyperion.sh set_hue4'
        command_state: '/home/homeassistant/.homeassistant/shell/switch_kodi_hyperion.sh num_lights'
        friendly_name: KODI Ambilight INMERSION
        value_template: '{{ value_json == 6 }}'

media_player:
  - platform: mykodi
    host: !secret kodi_host
    port: !secret kodi_port
    name: Kodi
    username: !secret kodi_user
    password: !secret kodi_pw
    enable_websocket: true
    timeout: 10
    turn_on_action:
    - service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: activate
    turn_off_action:
    - service: media_player.media_stop
      data:
        entity_id: media_player.kodi
    - service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: standby

shell_command:
  # Kill OSMC Kodi (when frozen)
  cmd_kill_kodi: !secret kill_kodi_cmd

script:
  play_kodi_pvr:
    alias: Enciende la caja tonta
    sequence:
      - alias: TV on
        service: media_player.turn_on
        data:
          entity_id: media_player.kodi

      - alias: Play TV channel
        service: media_player.play_media
        data_template:
          entity_id: media_player.kodi
    #      The type of the content to play. Must be one of MUSIC, TVSHOW, VIDEO, EPISODE, CHANNEL or PLAYLIST
          media_content_type: "CHANNEL"
          media_content_id: >
            {% if (now().hour < 14) or ((now().hour == 14) and (now().minute < 50)) %}
              10
            {% elif (now().hour < 16) %}
              15
            {% elif (now().hour < 20) %}
              2
            {% elif (now().hour == 20) and (now().minute < 50) %}
              10
            {% elif (now().hour == 20) or ((now().hour == 21) and (now().minute < 15)) %}
              15
            {% else %}
              10
            {% endif %}

      - alias: Notificación de selección de canal
        service: telegram_bot.send_message
        data_template:
          title: '*TV PVR ON*'
          target: '{{ states.sensor.telegram_default_chatid.state | int }}'
          disable_notification: true
          message: >
            Encendido de caja tonta en canal '{% if (now().hour < 14) or ((now().hour == 14) and (now().minute < 50)) %}laSexta HD{% elif (now().hour < 16) %}antena3 HD{% elif (now().hour < 20) %}24h{% elif (now().hour == 20) and (now().minute < 50) %}laSexta HD{% elif (now().hour == 20) or ((now().hour == 21) and (now().minute < 15)) %}antena3 HD{% else %}laSexta HD{% endif %}'.

  restart_kodi_osmc:
    alias: Restart KODI OSMC
    sequence:
      - service: notify.ios_iphone
        data:
          title: 'Reiniciando KODI OSMC'
          message: "KODI debería 'morir' y 'resucitar' en unos segundos"
          data:
            push:
              category: "CONFIRM"
      - service: telegram_bot.send_message
        data_template:
          title: 'Reiniciando KODI OSMC'
          target: '{{ states.sensor.telegram_default_chatid.state | int }}'
          message: "KODI debería 'morir' y 'resucitar' en unos segundos"
          disable_notification: true
      - service: shell_command.cmd_kill_kodi

  stop_kodi:
    alias: Stop playback in Kodi
    sequence:
        service: media_player.media_stop
        data:
          entity_id: media_player.kodi

  quit_kodi:
    alias: Quit Kodi
    sequence:
      service: media_player.kodi_call_method
      data:
        method: Application.Quit

  update_library:
    alias: Update Kodi Library
    sequence:
      - alias: Call Kodi update
        service: media_player.kodi_call_method
        data:
          entity_id: media_player.kodi
          method: VideoLibrary.Scan

  recent_movies:
    alias: Últimas películas
    sequence:
      - alias: Call Kodi serv
        service: media_player.kodi_call_method
        data:
          entity_id: media_player.kodi
          method: VideoLibrary.GetRecentlyAddedMovies
          properties:
            - title
            - year
            - file
            - lastplayed

  recent_episodes:
    alias: Últimos episodios
    sequence:
      - alias: Call Kodi serv
        service: media_player.kodi_call_method
        data:
          entity_id: media_player.kodi
          method: VideoLibrary.GetRecentlyAddedEpisodes
          properties:
            - showtitle
            - file
            - lastplayed
            - dateadded
            - firstaired

  pvr_channels:
    alias: Canales de TV
    sequence:
      - alias: Call Kodi serv
        service: media_player.kodi_call_method
        data:
          entity_id: media_player.kodi
          method: PVR.GetChannels
          channelgroupid: 1

input_select:
  kodi_results:
    name: Kodi API results
    options:
     - Nada que hacer

group:
  player:
    - media_player.kodi

  Kodi:
    control: hidden
    entities:
      - switch.toggle_kodi_ambilight
      - switch.toggle_config_kodi_ambilight
      - script.play_kodi_pvr
      - script.stop_kodi
      - script.update_library
      - script.quit_kodi
      - script.restart_kodi_osmc

  Media select:
    control: hidden
    entities:
      - script.recent_episodes
      - script.recent_movies
      - script.pvr_channels
      - input_select.kodi_results
