homeassistant:
  customize:
    vacuum.robot_aspirador:
      friendly_name: Aspiradora
      custom_ui_state_card: custom_vacuum

vacuum:
- platform: xiaomi
  # firmware: 3.3.9_003077
  name: robot_aspirador
  host: !secret xiaomi_vacuum_robot_ip
  token: !secret xiaomi_vacuum_robot_token

# TODO Automations
# - notify if robot get lost
# - notify if problem
# - use as alarm playing with commands!

group:
  Xiaomi Vacuum Robot:
    control: hidden
    entities:
      - vacuum.robot_aspirador
