homeassistant:
  customize:
    vacuum.robot_aspirador:
      friendly_name: Aspiradora
      custom_ui_state_card: custom_vacuum

vacuum:
- platform: xiaomi_miio
  # firmware: 3.3.9_003077
  name: robot_aspirador
  host: !secret xiaomi_vacuum_robot_ip
  token: !secret xiaomi_vacuum_robot_token

group:
  Xiaomi Vacuum Robot:
    control: hidden
    entities:
      - vacuum.robot_aspirador

automation:
- alias: Botvac error notification
  trigger:
    platform: state
    entity_id: vacuum.robot_aspirador
  condition:
    condition: template
    value_template: '{{ "error" in states.vacuum.robot_aspirador.attributes }}'
  action:
    service: telegram_bot.send_message
    data_template:
      title: '*Botvac Error*'
      message: >
        El robot aspirador ha fallado: _{{ states.vacuum.robot_aspirador.attributes.error }}_
        (Status: {{ states.vacuum.robot_aspirador.attributes.status }}, batt: {{ states.vacuum.robot_aspirador.attributes.battery_level }} %)
      target: '{{ states.sensor.telegram_default_chatid.state | int }}'
      disable_notification: false
      inline_keyboard:
        - Locate botvac:/service_call vacuum.locate vacuum.robot_aspirador, To dock:/service_call vacuum.return_to_home vacuum.robot_aspirador
        - Start:/service_call vacuum.start_pause vacuum.robot_aspirador, Stop:/service_call vacuum.stop vacuum.robot_aspirador, +:/init

# For the dev panel, in JSON:
#{"message": "El robot aspirador ha fallado: _{{ states.vacuum.robot_aspirador.attributes.Error }}_ (Status: {{ states.vacuum.robot_aspirador.attributes.status }}, batt: {{ states.vacuum.robot_aspirador.attributes.battery }} %)", "title": "*Botvac Error*", "target": "{{ states.sensor.telegram_default_chatid.state | int }}", "disable_notification": false, "inline_keyboard": ["Locate botvac:/service_call vacuum.locate vacuum.robot_aspirador, To dock:/service_call vacuum.return_to_home vacuum.robot_aspirador", "Start:/service_call vacuum.start_pause vacuum.robot_aspirador, Stop:/service_call vacuum.stop vacuum.robot_aspirador, +:/init"]}
